# -*- coding: utf-8 -*-
"""Offline translations for native/static dialog chrome.

Kept separate from the normal widget catalog because dialog bodies are often
long and native file dialogs cannot be repaired by the application event filter.
"""
from __future__ import annotations

import re

from ui.localization import LANG_EN, LANG_JA, LANG_ZH, normalize_language, translate_text

_EN = {
"AI尚未配置":"AI is not configured",
"选择图片文件夹":"Choose Image Folder",
"选择包含图片或 PDF 的文件夹":"Choose Folder Containing Images or PDFs",
"选择图片或 PDF（可多选）":"Choose Images or PDF (multiple selection allowed)",
"图片和PDF (*.png *.jpg *.jpeg *.heic *.tif *.tiff *.bmp *.gif *.pdf);;所有文件 (*)":"Images and PDF (*.png *.jpg *.jpeg *.heic *.tif *.tiff *.bmp *.gif *.pdf);;All Files (*)",
"删除页面":"Delete Pages",
"图片和PDF (*.png *.jpg *.jpeg *.heic *.tif *.tiff *.bmp *.gif *.pdf)":"Images and PDF (*.png *.jpg *.jpeg *.heic *.tif *.tiff *.bmp *.gif *.pdf)",
"重复执行确认":"Confirm Re-run",
"文本框有未应用修改":"Text boxes contain unapplied edits",
"处理前/处理后文本框里有尚未写回文档模型的修改。\n\n选择「Yes」会先应用编辑再继续；选择「No」会丢弃文本框临时修改并重新按文档模型刷新；选择「Cancel」取消当前操作。":"The Before/After text boxes contain edits that have not been written back to the document model.\n\nChoose Yes to apply the edits before continuing; No to discard the temporary edits and refresh from the document model; Cancel to cancel this operation.",
"导入待格式处理文本":"Import Text for Formatting",
"支持的格式 (*.json *.md *.markdown *.txt);;JSON (*.json);;Markdown (*.md *.markdown);;文本 (*.txt)":"Supported Files (*.json *.md *.markdown *.txt);;JSON (*.json);;Markdown (*.md *.markdown);;Text (*.txt)",
"支持的格式 (*.json *.xml *.tei *.md *.markdown *.txt);;TEI P5 XML (*.xml *.tei);;JSON (*.json);;Markdown (*.md *.markdown);;文本 (*.txt)":"Supported Files (*.json *.xml *.tei *.md *.markdown *.txt);;TEI P5 XML (*.xml *.tei);;JSON (*.json);;Markdown (*.md *.markdown);;Text (*.txt)",
"导入 Word 文档（已识别）":"Import Recognized Word Document",
"Word 文档 (*.docx *.doc)":"Word Documents (*.docx *.doc)",
"导入完成":"Import Complete",
"导入 EPUB":"Import EPUB",
"保存 Formatter 结果":"Save Formatter Result",
"保存 JSON":"Save JSON",
"导出 DOCX":"Export DOCX",
"选择本书断点目录":"Choose Checkpoint Folder for This Book",
"新建格式":"New Format",
"格式名称:":"Format Name:",
"选择参考 EPUB（日文/中文）":"Choose Reference EPUB (Japanese/Chinese)",
"格式名称":"Format Name",
"给学到的格式起个名字:":"Name the learned format:",
"格式已保存":"Format Saved",
"删除格式":"Delete Format",
"导出格式":"Export Format",
"导入格式":"Import Format",
"选择全书术语白名单":"Choose Full-book Glossary Allowlist",
"术语表 (*.txt *.tsv *.csv *.json);;所有文件 (*)":"Glossary (*.txt *.tsv *.csv *.json);;All Files (*)",
"选择项目目录":"Choose Project Folder",
"载入工作文档":"Load Working Document",
"选择校对文本来源":"Choose Proofreading Text Source",
"支持格式 (*.json *.md *.markdown *.txt *.docx *.epub *.html *.htm)":"Supported Files (*.json *.md *.markdown *.txt *.docx *.epub *.html *.htm)",
"清空版本":"Clear Version",
"保存 EPUB":"Save EPUB",
"选择 PDF 文件":"Choose PDF File",
"仍采用了高风险 AI 修改":"High-risk AI changes are still accepted",
"导入参考原文（出版前草稿 / Web版 / 校对稿）":"Import Reference Source (pre-publication draft / web version / proof)",
"文本/文档 (*.txt *.md);;所有文件 (*)":"Text/Documents (*.txt *.md);;All Files (*)",
"导入外部 OCR":"Import External OCR",
"OCR/文本 (*.txt *.md *.markdown *.json *.docx *.epub *.html *.htm);;所有文件 (*)":"OCR/Text (*.txt *.md *.markdown *.json *.docx *.epub *.html *.htm);;All Files (*)",
"文本/文档 (*.txt *.md *.json);;所有文件 (*)":"Text/Documents (*.txt *.md *.json);;All Files (*)",
"选择导出目录":"Choose Export Folder",
"导出完成":"Export Complete",
"确定性修复完成":"Deterministic Repair Complete",
"可信正文已套入 OCR 版面":"Trusted Text Applied to OCR Layout",
"选择出版级参考文本":"Choose Publication-grade Reference Text",
"参考文本 (*.epub *.txt *.md *.markdown *.docx *.json *.html *.htm);;所有文件 (*)":"Reference Text (*.epub *.txt *.md *.markdown *.docx *.json *.html *.htm);;All Files (*)",
"选择术语表":"Choose Glossary",
"选择 AI 审定结果目录":"Choose AI Adjudication Result Folder",
"导出单 OCR 大模型校对包":"Export Single-OCR LLM Review Package",
"JSON 校对包 (*.json);;Markdown 校对包 (*.md)":"JSON Review Package (*.json);;Markdown Review Package (*.md)",
"导入单 OCR 大模型校对包":"Import Single-OCR LLM Review Package",
"OCR 校对包 (*.json *.md *.markdown)":"OCR Review Package (*.json *.md *.markdown)",
"单 OCR 校对包已应用":"Single-OCR Review Package Applied",
"无损标准化完成":"Lossless Normalization Complete",
"导出多模型 OCR 大模型对比包":"Export Multi-model OCR LLM Comparison Package",
"导出多模型 AI OCR 裁决包":"Export Multi-model AI OCR Adjudication Package",
"导出 V5 多模型 AI OCR 裁决包":"Export V5 Multi-model AI OCR Adjudication Package",
"ZIP 纠错包 (*.zip)":"ZIP Correction Package (*.zip)",
"OCR 逐模型纠错／最终裁决包已导出":"Per-model OCR Correction / Final Adjudication Package Exported",
"恢复多模型 OCR 裁决会话":"Restore Multi-model OCR Adjudication Session",
"AI OCR 裁决包/旧逐模型包 (*.zip)":"AI OCR Adjudication / Legacy Per-model Package (*.zip)",
"多模型 OCR 会话已恢复":"Multi-model OCR Session Restored",
"导入 AI OCR 裁决结果":"Import AI OCR Adjudication Result",
"AI OCR 裁决/旧逐模型结果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)":"AI OCR Adjudication / Legacy Per-model Result (*.json *.zip);;JSON (*.json);;ZIP (*.zip)",
"AI OCR 纠错已非破坏式导入":"AI OCR Corrections Imported Non-destructively",
"导出融合结果与骨架 EPUB":"Export Fusion Result and Skeleton EPUB",
"ZIP 包 (*.zip)":"ZIP Package (*.zip)",
"融合结果与骨架 EPUB 已导出":"Fusion Result and Skeleton EPUB Exported",
"选择 AI 修复包 V4 的保存位置":"Choose Save Location for AI Repair Package V4",
"AI 修复包导出完成":"AI Repair Package Export Complete",
"导入外部 AI 修复结果（推荐稀疏 JSON）":"Import External AI Repair Result (sparse JSON recommended)",
"推荐：稀疏 JSON (*.json);;兼容：AI 修复 EPUB (*.epub);;全部支持格式 (*.json *.epub)":"Recommended: Sparse JSON (*.json);;Compatible: AI Repair EPUB (*.epub);;All Supported Files (*.json *.epub)",
"AI 修复结果已载入":"AI Repair Result Loaded",
"选择需要修复的旧版多模型 OCR 包":"Choose Legacy Multi-model OCR Package to Repair",
"保存对齐修复包":"Save Alignment Repair Package",
"旧版对齐包修复完成":"Legacy Alignment Package Repair Complete",
"导入多模型 OCR 大模型融合包":"Import Multi-model OCR LLM Fusion Package",
"选择分别导出 OCR 文本的文件夹":"Choose Folder for Separate OCR Text Exports",
"分别导出完成":"Separate Export Complete",
"OCR 融合稿已应用":"OCR Fusion Draft Applied",
"图文校对稿已应用":"Image/Text Review Draft Applied",
"手动更新完成":"Manual Update Complete",
"OCR 模型操作失败":"OCR Model Operation Failed",
"设备检测失败":"Device Detection Failed",
"确认更新程序":"Confirm Application Update",
"更新完成":"Update Complete",
"诊断信息":"Diagnostics",
"诊断信息已复制到剪贴板。":"Diagnostics copied to the clipboard.",
"选择 PaddleOCR-VL 输出":"Choose PaddleOCR-VL Output",
"尚未打开书籍":"No Book Open",
"请先添加图片、PDF 或打开图片文件夹。":"Add images/PDF or open an image folder first.",
"OCR 正在运行":"OCR Is Running",
"请先停止或完成当前 OCR，再更换页面源。":"Stop or finish the current OCR before changing the page source.",
"请先停止或完成当前 OCR，再恢复页面源。":"Stop or finish the current OCR before restoring the page source.",
"无图片":"No Images",
"未找到可用的图片":"No usable images were found",
"请先停止或完成当前 OCR，再删除页面。\n正在运行的 Apple OCR/多模型任务已经冻结了页面队列，运行中修改页面会造成结果错位。":"Stop or finish the current OCR before deleting pages.\nThe running Apple OCR/multi-model task has frozen the page queue; changing pages during the run would misalign results.",
"提示":"Notice",
"请先点选要删除的页面（可多选，或拖框多选）":"Select the pages to delete first (multiple selection or drag selection is supported).",
"请先点选页面（可多选）":"Select one or more pages first.",
"请先停止或完成当前 OCR，再切换识别模式。":"Stop or finish the current OCR before switching recognition mode.",
"本地 OCR 检测结果":"Local OCR Detection Result",
"OCR 环境检测失败":"OCR Runtime Detection Failed",
"请先停止或完成当前 OCR，再安装/修复 PaddleOCR 模型。":"Stop or finish the current OCR before installing/repairing PaddleOCR models.",
"PaddleOCR 已就绪":"PaddleOCR Ready",
"当前 PaddleOCR 环境和模型已经完成初始化。现在可以直接开始 OCR；后续不会重复下载已缓存的模型。":"The PaddleOCR environment and models are initialized. You can start OCR now; cached models will not be downloaded again.",
}

_JA = {
"AI尚未配置":"AIが未設定です",
"选择图片文件夹":"画像フォルダを選択",
"选择包含图片或 PDF 的文件夹":"画像またはPDFを含むフォルダーを選択",
"选择图片或 PDF（可多选）":"画像またはPDFを選択（複数選択可）",
"图片和PDF (*.png *.jpg *.jpeg *.heic *.tif *.tiff *.bmp *.gif *.pdf);;所有文件 (*)":"画像とPDF (*.png *.jpg *.jpeg *.heic *.tif *.tiff *.bmp *.gif *.pdf);;すべてのファイル (*)",
"删除页面":"ページを削除",
"图片和PDF (*.png *.jpg *.jpeg *.heic *.tif *.tiff *.bmp *.gif *.pdf)":"画像とPDF (*.png *.jpg *.jpeg *.heic *.tif *.tiff *.bmp *.gif *.pdf)",
"重复执行确认":"再実行の確認",
"文本框有未应用修改":"未適用の編集があります",
"处理前/处理后文本框里有尚未写回文档模型的修改。\n\n选择「Yes」会先应用编辑再继续；选择「No」会丢弃文本框临时修改并重新按文档模型刷新；选择「Cancel」取消当前操作。":"処理前/処理後テキスト欄に、まだ文書モデルへ書き戻していない編集があります。\n\n「Yes」は編集を適用して続行、「No」は一時編集を破棄して文書モデルから再読込、「Cancel」は操作を中止します。",
"导入待格式处理文本":"整形対象テキストを読み込む",
"支持的格式 (*.json *.md *.markdown *.txt);;JSON (*.json);;Markdown (*.md *.markdown);;文本 (*.txt)":"対応形式 (*.json *.md *.markdown *.txt);;JSON (*.json);;Markdown (*.md *.markdown);;テキスト (*.txt)",
"支持的格式 (*.json *.xml *.tei *.md *.markdown *.txt);;TEI P5 XML (*.xml *.tei);;JSON (*.json);;Markdown (*.md *.markdown);;文本 (*.txt)":"対応形式 (*.json *.xml *.tei *.md *.markdown *.txt);;TEI P5 XML (*.xml *.tei);;JSON (*.json);;Markdown (*.md *.markdown);;テキスト (*.txt)",
"导入 Word 文档（已识别）":"認識済みWord文書を読み込む",
"Word 文档 (*.docx *.doc)":"Word文書 (*.docx *.doc)",
"导入完成":"読み込み完了",
"导入 EPUB":"EPUBを読み込む",
"保存 Formatter 结果":"Formatter結果を保存",
"保存 JSON":"JSONを保存",
"导出 DOCX":"DOCXを書き出す",
"选择本书断点目录":"この本のチェックポイントフォルダを選択",
"新建格式":"新規フォーマット",
"格式名称:":"フォーマット名:",
"选择参考 EPUB（日文/中文）":"参照EPUB（日本語/中国語）を選択",
"格式名称":"フォーマット名",
"给学到的格式起个名字:":"学習したフォーマットの名前:",
"格式已保存":"フォーマットを保存しました",
"删除格式":"フォーマットを削除",
"导出格式":"フォーマットを書き出す",
"导入格式":"フォーマットを読み込む",
"选择全书术语白名单":"全書用語ホワイトリストを選択",
"术语表 (*.txt *.tsv *.csv *.json);;所有文件 (*)":"用語集 (*.txt *.tsv *.csv *.json);;すべてのファイル (*)",
"选择项目目录":"プロジェクトフォルダを選択",
"载入工作文档":"作業文書を読み込む",
"选择校对文本来源":"校正テキストのソースを選択",
"支持格式 (*.json *.md *.markdown *.txt *.docx *.epub *.html *.htm)":"対応形式 (*.json *.md *.markdown *.txt *.docx *.epub *.html *.htm)",
"清空版本":"バージョンを消去",
"保存 EPUB":"EPUBを保存",
"选择 PDF 文件":"PDFファイルを選択",
"仍采用了高风险 AI 修改":"高リスクのAI変更がまだ採用されています",
"导入参考原文（出版前草稿 / Web版 / 校对稿）":"参照原文（出版前草稿 / Web版 / 校正稿）を読み込む",
"文本/文档 (*.txt *.md);;所有文件 (*)":"テキスト/文書 (*.txt *.md);;すべてのファイル (*)",
"导入外部 OCR":"外部OCRを読み込む",
"OCR/文本 (*.txt *.md *.markdown *.json *.docx *.epub *.html *.htm);;所有文件 (*)":"OCR/テキスト (*.txt *.md *.markdown *.json *.docx *.epub *.html *.htm);;すべてのファイル (*)",
"文本/文档 (*.txt *.md *.json);;所有文件 (*)":"テキスト/文書 (*.txt *.md *.json);;すべてのファイル (*)",
"选择导出目录":"出力フォルダを選択",
"导出完成":"書き出し完了",
"确定性修复完成":"決定論的修復が完了しました",
"可信正文已套入 OCR 版面":"信頼本文をOCRレイアウトへ適用しました",
"选择出版级参考文本":"出版品質の参照テキストを選択",
"参考文本 (*.epub *.txt *.md *.markdown *.docx *.json *.html *.htm);;所有文件 (*)":"参照テキスト (*.epub *.txt *.md *.markdown *.docx *.json *.html *.htm);;すべてのファイル (*)",
"选择术语表":"用語集を選択",
"选择 AI 审定结果目录":"AI裁決結果フォルダを選択",
"导出单 OCR 大模型校对包":"単一OCR LLM校正パッケージを書き出す",
"JSON 校对包 (*.json);;Markdown 校对包 (*.md)":"JSON校正パッケージ (*.json);;Markdown校正パッケージ (*.md)",
"导入单 OCR 大模型校对包":"単一OCR LLM校正パッケージを読み込む",
"OCR 校对包 (*.json *.md *.markdown)":"OCR校正パッケージ (*.json *.md *.markdown)",
"单 OCR 校对包已应用":"単一OCR校正パッケージを適用しました",
"无损标准化完成":"無損失正規化が完了しました",
"导出多模型 OCR 大模型对比包":"複数OCR LLM比較パッケージを書き出す",
"导出多模型 AI OCR 裁决包":"複数モデルAI OCR裁決パッケージを書き出す",
"导出 V5 多模型 AI OCR 裁决包":"V5複数モデルAI OCR裁決パッケージを書き出す",
"ZIP 纠错包 (*.zip)":"ZIP修正パッケージ (*.zip)",
"OCR 逐模型纠错／最终裁决包已导出":"OCRモデル別修正／最終裁決パッケージを書き出しました",
"恢复多模型 OCR 裁决会话":"複数モデルOCR裁決セッションを復元",
"AI OCR 裁决包/旧逐模型包 (*.zip)":"AI OCR裁決/旧モデル別パッケージ (*.zip)",
"多模型 OCR 会话已恢复":"複数モデルOCRセッションを復元しました",
"导入 AI OCR 裁决结果":"AI OCR裁決結果を読み込む",
"AI OCR 裁决/旧逐模型结果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)":"AI OCR裁決/旧モデル別結果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)",
"AI OCR 纠错已非破坏式导入":"AI OCR修正を非破壊で読み込みました",
"导出融合结果与骨架 EPUB":"融合結果と骨格EPUBを書き出す",
"ZIP 包 (*.zip)":"ZIPパッケージ (*.zip)",
"融合结果与骨架 EPUB 已导出":"融合結果と骨格EPUBを書き出しました",
"选择 AI 修复包 V4 的保存位置":"AI修復パッケージV4の保存先を選択",
"AI 修复包导出完成":"AI修復パッケージの書き出し完了",
"导入外部 AI 修复结果（推荐稀疏 JSON）":"外部AI修復結果を読み込む（疎JSON推奨）",
"推荐：稀疏 JSON (*.json);;兼容：AI 修复 EPUB (*.epub);;全部支持格式 (*.json *.epub)":"推奨：疎JSON (*.json);;互換：AI修復EPUB (*.epub);;全対応形式 (*.json *.epub)",
"AI 修复结果已载入":"AI修復結果を読み込みました",
"选择需要修复的旧版多模型 OCR 包":"修復する旧版複数OCRパッケージを選択",
"保存对齐修复包":"整列修復パッケージを保存",
"旧版对齐包修复完成":"旧版整列パッケージの修復完了",
"导入多模型 OCR 大模型融合包":"複数OCR LLM融合パッケージを読み込む",
"选择分别导出 OCR 文本的文件夹":"OCRテキスト個別出力フォルダを選択",
"分别导出完成":"個別書き出し完了",
"OCR 融合稿已应用":"OCR融合稿を適用しました",
"图文校对稿已应用":"画像/テキスト校正稿を適用しました",
"手动更新完成":"手動更新完了",
"OCR 模型操作失败":"OCRモデル操作に失敗しました",
"设备检测失败":"デバイス検出に失敗しました",
"确认更新程序":"アプリ更新の確認",
"更新完成":"更新完了",
"诊断信息":"診断情報",
"诊断信息已复制到剪贴板。":"診断情報をクリップボードへコピーしました。",
"选择 PaddleOCR-VL 输出":"PaddleOCR-VL出力を選択",
"尚未打开书籍":"本が開かれていません",
"请先添加图片、PDF 或打开图片文件夹。":"先に画像/PDFを追加するか、画像フォルダを開いてください。",
"OCR 正在运行":"OCR実行中",
"请先停止或完成当前 OCR，再更换页面源。":"現在のOCRを停止または完了してからページソースを変更してください。",
"请先停止或完成当前 OCR，再恢复页面源。":"現在のOCRを停止または完了してからページソースを復元してください。",
"无图片":"画像なし",
"未找到可用的图片":"利用できる画像が見つかりません",
"请先停止或完成当前 OCR，再删除页面。\n正在运行的 Apple OCR/多模型任务已经冻结了页面队列，运行中修改页面会造成结果错位。":"現在のOCRを停止または完了してからページを削除してください。\n実行中のApple OCR/複数モデルタスクはページキューを固定しているため、実行中にページを変更すると結果がずれます。",
"提示":"お知らせ",
"请先点选要删除的页面（可多选，或拖框多选）":"削除するページを先に選択してください（複数選択・ドラッグ選択可）。",
"请先点选页面（可多选）":"先にページを選択してください（複数選択可）。",
"请先停止或完成当前 OCR，再切换识别模式。":"現在のOCRを停止または完了してから認識モードを切り替えてください。",
"本地 OCR 检测结果":"ローカルOCR検出結果",
"OCR 环境检测失败":"OCR実行環境の検出に失敗しました",
"请先停止或完成当前 OCR，再安装/修复 PaddleOCR 模型。":"現在のOCRを停止または完了してからPaddleOCRモデルをインストール/修復してください。",
"PaddleOCR 已就绪":"PaddleOCR準備完了",
"当前 PaddleOCR 环境和模型已经完成初始化。现在可以直接开始 OCR；后续不会重复下载已缓存的模型。":"PaddleOCR環境とモデルの初期化が完了しました。すぐOCRを開始でき、キャッシュ済みモデルを再ダウンロードしません。",
}


# AI image-processing dialogs are explicit offline chrome; user content/errors
# remain untranslated by the dialog localization layer.
_EN.update({
    "没有页面": "No Pages",
    "请先在“页面管理”导入 PDF、单张图片、多个图片或图片文件夹。": "Import a PDF, image, multiple images, or an image folder in Page Manager first.",
    "没有测试图片": "No Test Image",
    "请先在页面管理导入至少一页。": "Import at least one page in Page Manager first.",
    "请先在页面管理中导入图片或 PDF": "Import images or a PDF in Page Manager first.",
    "将发送一张缩小到最长边 768px 的当前书页到所选 API。此操作会产生一次很小的真实 API 用量。继续？": "A current book page reduced to a 768 px long edge will be sent to the selected API. This uses a very small amount of real API quota. Continue?",
})
_JA.update({
    "没有页面": "ページがありません",
    "请先在“页面管理”导入 PDF、单张图片、多个图片或图片文件夹。": "先にページ管理でPDF、単一画像、複数画像、または画像フォルダを読み込んでください。",
    "没有测试图片": "テスト画像がありません",
    "请先在页面管理导入至少一页。": "先にページ管理で少なくとも1ページを読み込んでください。",
    "请先在页面管理中导入图片或 PDF": "先にページ管理で画像またはPDFを読み込んでください。",
    "将发送一张缩小到最长边 768px 的当前书页到所选 API。此操作会产生一次很小的真实 API 用量。继续？": "現在の書籍ページ1枚を長辺768pxへ縮小して選択中のAPIへ送信します。ごく少量の実API使用量が発生します。続行しますか？",
})


def _translate_dialog_atom(source: str, language: str) -> str:
    """Translate one complete UI fragment while preserving unknown/user data."""
    if not source:
        return source
    base = translate_text(source, language)
    if base != source:
        return base
    exact = (_JA if language == LANG_JA else _EN).get(source)
    if exact is not None:
        return exact
    for pattern, replacer in _DIALOG_LINE_PATTERNS.get(language, ()):
        match = pattern.fullmatch(source)
        if match:
            return replacer(match)
    return source


def translate_dialog_text(text: str | None, language: str) -> str:
    """Translate dialog chrome only, never free-form document/error payloads.

    Dynamic dialogs are translated through a small whitelist of anchored line
    templates.  Captured paths, model names, counts and other payload values
    are inserted verbatim, so localization cannot mutate business identifiers.
    """
    source = "" if text is None else str(text)
    language = normalize_language(language)
    if language == LANG_ZH or not source:
        return source

    whole = _translate_dialog_atom(source, language)
    if whole != source or "\n" not in source:
        return whole

    # Long status dialogs are assembled from stable UI lines plus dynamic
    # values. Translate each complete line independently and preserve newlines
    # byte-for-byte. Unknown lines (tracebacks, paths, OCR/model output) remain
    # untouched.
    parts = source.splitlines(keepends=True)
    out: list[str] = []
    for part in parts:
        body = part.rstrip("\r\n")
        ending = part[len(body):]
        out.append(_translate_dialog_atom(body, language) + ending)
    return "".join(out)

# Extended runtime warnings / workflow confirmations discovered by the deep UI audit.
_EN.update({
"先安装 OpenVINO Runtime":"Install OpenVINO Runtime First",
"手写模型":"Handwriting Model",
"OpenVINO 日语手写备用模型已下载并校验完成。":"The OpenVINO Japanese handwriting fallback model was downloaded and verified.",
"当前模式不支持":"Not Supported in Current Mode",
"日语逐字审校仅属于日文竖排模式，不会接入简体中文横排 OCR。":"Japanese character-by-character review is available only in Japanese vertical mode and is not connected to Simplified Chinese horizontal OCR.",
"Token 为空；如需删除系统中已保存的 Token，请点击“清除”。":"The token is empty. To delete a token saved in the system, click Clear.",
"已保存到系统凭据库；不会写入项目文件或 OCR 模式快照。":"Saved to the system credential store; it will not be written to project files or OCR-mode snapshots.",
"保存失败；当前输入框中的 Token 仍可用于本次运行。":"Save failed; the token currently entered can still be used for this run.",
"无法预览":"Preview Unavailable",
"请先选择图片或 PDF。":"Choose an image or PDF first.",
"请先固定正文区域":"Fix the Body Region First",
"请先在右侧图片上拖框选定纯正文区域，再预览分列。":"Drag a box on the image at right to select a body-only region before previewing columns.",
"当前 OCR 尚未结束，请先停止或等待完成。":"The current OCR is still running. Stop it or wait for completion first.",
"PaddleOCR 正在准备":"PaddleOCR Is Preparing",
"模型安装/修复完成后再开始 OCR，避免同时写入模型缓存。":"Start OCR after model installation/repair completes to avoid concurrent writes to the model cache.",
"已移除无效 OCR 页面":"Invalid OCR Pages Removed",
"错误":"Error",
"请先选择文件夹或文件":"Choose a folder or file first",
"OCR 模式与引擎冲突":"OCR Mode / Engine Conflict",
"OCR 模型重复":"Duplicate OCR Model",
"多模型 OCR 对比中不能重复选择同一个模型。":"The same model cannot be selected more than once in multi-model OCR comparison.",
"请选择模型":"Choose Models",
"多模型 OCR 对比至少需要模型1和模型2。":"Multi-model OCR comparison requires at least Model 1 and Model 2.",
"无法应用编辑":"Cannot Apply Edits",
"还没有处理前内容可载入":"There is no pre-processing content to load yet",
"还没有处理结果":"There is no processing result yet",
"没有可撤销的步骤":"There is no step to undo",
"未选择规则":"No Rules Selected",
"格式规则默认全部关闭，请先勾选需要运行的规则。":"Formatting rules are off by default. Select the rules you want to run first.",
"请先完成 OCR 或载入 JSON":"Complete OCR or load JSON first",
"任务进行中":"Task in Progress",
"请先等待当前 Formatter 任务完成，或停止正在运行的 AI 任务。":"Wait for the current Formatter task to finish, or stop the running AI task first.",
"清除断点":"Clear Checkpoint",
"Formatter AI 任务尚未完成":"Formatter AI task has not finished yet",
"请先等待当前 Formatter 导入或本地规则任务完成。":"Wait for the current Formatter import or local-rule task to finish first.",
"请先导入文档或完成 OCR":"Import a document or complete OCR first",
"未发现 CSS":"No CSS Found",
"请输入格式名称":"Enter a format name",
"内置模板不支持导出，请先选中一个自定义格式":"Built-in templates cannot be exported. Select a custom format first.",
"读取模型失败":"Failed to Load Models",
"配置不完整":"Incomplete Configuration",
"无法保存":"Cannot Save",
"请先等待当前替换或 AI 任务结束，或切换新书以安全丢弃旧结果。":"Wait for the current replacement/AI task to finish, or switch to a new book to safely discard the old result.",
"请先载入 OCR 文档和替换文本":"Load the OCR document and replacement text first",
"文本比较完成":"Text Comparison Complete",
"替换版本已过期":"Replacement Version Is Stale",
"请先等待当前替换或 AI 任务结束，避免两个任务同时改写同一版本。":"Wait for the current replacement or AI task to finish so two tasks do not rewrite the same version at once.",
"当前任务结束前不能恢复 AI 版本。":"The AI version cannot be restored until the current task ends.",
"已保存":"Saved",
"保存版本":"Save Version",
"当前任务结束前不能清空正文版本。":"Body-text versions cannot be cleared until the current task ends.",
"版本已过期":"Version Is Stale",
"上游 OCR/Formatter 正文已经更新，此版本仍基于旧正文。\n\n旧版本会被保留，但直接导出可能混入旧句子。仍要明确使用它制作 EPUB 吗？":"The upstream OCR/Formatter text has changed, while this version is still based on older text.\n\nThe old version will be kept, but exporting it directly may mix in stale sentences. Do you explicitly want to build the EPUB from it?",
"剪贴板为空":"Clipboard Is Empty",
"剪贴板中没有可粘贴的书名。":"There is no book title in the clipboard to paste.",
"EPUB 正在生成":"EPUB Is Being Built",
"当前已有一个 EPUB 构建任务，请等待完成后再生成。":"An EPUB build is already running. Wait for it to finish before starting another.",
"请先完成 OCR 和格式处理":"Complete OCR and formatting first",
"翻译/发布前检查发现问题":"Pre-publication Check Found Problems",
"旧正文快照已导出":"Old Text Snapshot Exported",
"提取进行中":"Extraction in Progress",
"当前 PDF 正在提取。切换新书会安全丢弃旧任务结果。":"The current PDF is being extracted. Switching to a new book will safely discard the old task result.",
"请先选择 PDF 文件":"Choose a PDF file first",
"先确认当前结果":"Confirm the Current Result First",
"请先接受或拒绝当前 AI 结果，再开始下一次处理。":"Accept or reject the current AI result before starting the next operation.",
"AI修改":"AI Changes",
"当前没有可见的 AI 文本修改。":"There are no visible AI text changes.",
"尚未导入参考原文":"Reference Source Not Imported",
"请先导入出版前草稿、Web版或校对稿。":"Import a pre-publication draft, web version or proof first.",
"没有可评分版本":"No Version Available for Scoring",
"请先载入 OCR、Formatter 或 AI 结果。":"Load an OCR, Formatter or AI result first.",
"缺少 OCR 版本":"OCR Version Missing",
"请先载入内置 OCR，并导入至少一份外部 OCR。":"Load the built-in OCR and import at least one external OCR first.",
"无法生成融合稿":"Cannot Generate Fusion Draft",
"请先载入内置 OCR，并导入/选择一份外部 OCR。":"Load the built-in OCR and import/select an external OCR first.",
"没有融合报告":"No Fusion Report",
"请先生成双 OCR 融合稿。":"Generate a two-OCR fusion draft first.",
"请先确认 AI 结果":"Confirm AI Result First",
"当前仍有待确认的 AI 修改。请先逐项确认或拒绝，再运行发布修复。":"There are still AI changes awaiting confirmation. Confirm or reject them one by one before running publication repair.",
"没有可确定修复的问题":"No Deterministic Repairs Found",
"未发现能在不猜测原文的前提下自动修复的问题。其余项目需要人工或局部 AI 核对。":"No issue can be repaired automatically without guessing the source text. Remaining items require manual or local AI review.",
"当前 AI 结果仍处于待确认状态。请先确认或拒绝，再把右侧作为可信正文套入版面。":"The current AI result is still awaiting confirmation. Confirm or reject it before applying the right-side text as trusted text to the layout.",
"缺少 OCR 版面":"OCR Layout Missing",
"请先载入 OCR/页面管理文档，再套入右侧可信正文。":"Load the OCR/Page Manager document before applying the trusted right-side text.",
"右侧正文过少":"Too Little Text on the Right",
"右侧没有足够正文，已取消可信正文覆盖。":"There is not enough body text on the right; trusted-text replacement was cancelled.",
"确认使用参考原文覆盖":"Confirm Reference-source Replacement",
"当前右侧是参考/草稿文本。草稿可能与正式出版版存在作者增删改写。\n\n继续后，右侧文字将成为全部最终正文，旧 OCR 文字会彻底删除；OCR 只保留页码、目录和插图。是否继续？":"The right side currently contains reference/draft text. The draft may differ from the published edition because of author additions, deletions or rewrites.\n\nIf you continue, the right-side text becomes the entire final body text and old OCR text will be removed; OCR will retain only page numbers, TOC and illustrations. Continue?",
"参考原文不能直接写回":"Reference Source Cannot Be Written Back Directly",
"出版前草稿只用于对照和裁决 AI 修改。正式出版版可能包含作者后续新增、删改和重排，不能用草稿全文覆盖 OCR/Formatter 结果。":"A pre-publication draft is only for comparison and AI-change adjudication. The published edition may contain later additions, deletions, rewrites or rearrangements, so the draft must not replace the entire OCR/Formatter result.",
"当前 AI 结果仍处于待确认状态。请先查看修改，然后点击“确认AI结果（仅右侧）”或“接受并应用”。":"The current AI result is still awaiting confirmation. Review the changes, then click “Confirm AI Result (right side only)” or “Accept and Apply”.",
"右侧没有可写回的文档版本":"There is no writable document version on the right",
"参考文件不存在":"Reference file does not exist",
"术语表不存在":"Glossary file does not exist",
"没有可载入结果":"No Result to Load",
"请先在 OCR 识别页完成一次单模型 OCR。":"Run a single-model OCR once in the OCR workspace first.",
})

_JA.update({
"先安装 OpenVINO Runtime":"先にOpenVINO Runtimeをインストールしてください",
"手写模型":"手書きモデル",
"OpenVINO 日语手写备用模型已下载并校验完成。":"OpenVINO日本語手書き予備モデルのダウンロードと検証が完了しました。",
"当前模式不支持":"現在のモードでは利用できません",
"日语逐字审校仅属于日文竖排模式，不会接入简体中文横排 OCR。":"日本語の文字単位校正は日本語縦書きモード専用で、簡体字中国語横書きOCRには接続しません。",
"Token 为空；如需删除系统中已保存的 Token，请点击“清除”。":"Tokenが空です。システムに保存済みのTokenを削除する場合は「クリア」をクリックしてください。",
"已保存到系统凭据库；不会写入项目文件或 OCR 模式快照。":"システム資格情報ストアへ保存しました。プロジェクトファイルやOCRモードスナップショットには書き込みません。",
"保存失败；当前输入框中的 Token 仍可用于本次运行。":"保存に失敗しました。現在入力されているTokenは今回の実行では引き続き使用できます。",
"无法预览":"プレビューできません",
"请先选择图片或 PDF。":"先に画像またはPDFを選択してください。",
"请先固定正文区域":"先に本文領域を固定してください",
"请先在右侧图片上拖框选定纯正文区域，再预览分列。":"右側画像で本文だけの領域をドラッグ選択してから列分割をプレビューしてください。",
"当前 OCR 尚未结束，请先停止或等待完成。":"現在のOCRはまだ終了していません。停止するか完了を待ってください。",
"PaddleOCR 正在准备":"PaddleOCRを準備中です",
"模型安装/修复完成后再开始 OCR，避免同时写入模型缓存。":"モデルのインストール/修復完了後にOCRを開始し、モデルキャッシュへの同時書き込みを避けてください。",
"已移除无效 OCR 页面":"無効なOCRページを除外しました",
"错误":"エラー",
"请先选择文件夹或文件":"先にフォルダまたはファイルを選択してください",
"OCR 模式与引擎冲突":"OCRモードとエンジンが競合しています",
"OCR 模型重复":"OCRモデルが重複しています",
"多模型 OCR 对比中不能重复选择同一个模型。":"複数モデルOCR比較では同じモデルを重複選択できません。",
"请选择模型":"モデルを選択してください",
"多模型 OCR 对比至少需要模型1和模型2。":"複数モデルOCR比較には少なくともモデル1とモデル2が必要です。",
"无法应用编辑":"編集を適用できません",
"还没有处理前内容可载入":"読み込める処理前内容がまだありません",
"还没有处理结果":"処理結果がまだありません",
"没有可撤销的步骤":"取り消せる手順がありません",
"未选择规则":"ルールが選択されていません",
"格式规则默认全部关闭，请先勾选需要运行的规则。":"整形ルールは既定ですべてオフです。実行するルールを先に選択してください。",
"请先完成 OCR 或载入 JSON":"先にOCRを完了するかJSONを読み込んでください",
"任务进行中":"タスク実行中",
"请先等待当前 Formatter 任务完成，或停止正在运行的 AI 任务。":"現在のFormatterタスク完了を待つか、実行中のAIタスクを停止してください。",
"清除断点":"チェックポイントを消去",
"Formatter AI 任务尚未完成":"Formatter AIタスクがまだ完了していません",
"请先等待当前 Formatter 导入或本地规则任务完成。":"現在のFormatter読み込みまたはローカルルールタスクの完了を待ってください。",
"请先导入文档或完成 OCR":"先に文書を読み込むかOCRを完了してください",
"未发现 CSS":"CSSが見つかりません",
"请输入格式名称":"フォーマット名を入力してください",
"内置模板不支持导出，请先选中一个自定义格式":"内蔵テンプレートは書き出せません。先にカスタムフォーマットを選択してください。",
"读取模型失败":"モデル一覧の読み込みに失敗しました",
"配置不完整":"設定が不完全です",
"无法保存":"保存できません",
"请先等待当前替换或 AI 任务结束，或切换新书以安全丢弃旧结果。":"現在の置換/AIタスクの終了を待つか、新しい本へ切り替えて古い結果を安全に破棄してください。",
"请先载入 OCR 文档和替换文本":"先にOCR文書と置換テキストを読み込んでください",
"替换版本已过期":"置換バージョンが古くなっています",
"请先等待当前替换或 AI 任务结束，避免两个任务同时改写同一版本。":"同じバージョンを2タスクが同時に書き換えないよう、現在の置換またはAIタスク終了を待ってください。",
"当前任务结束前不能恢复 AI 版本。":"現在のタスクが終了するまでAIバージョンを復元できません。",
"已保存":"保存しました",
"保存版本":"バージョンを保存",
"当前任务结束前不能清空正文版本。":"現在のタスクが終了するまで本文バージョンを消去できません。",
"版本已过期":"バージョンが古くなっています",
"上游 OCR/Formatter 正文已经更新，此版本仍基于旧正文。\n\n旧版本会被保留，但直接导出可能混入旧句子。仍要明确使用它制作 EPUB 吗？":"上流のOCR/Formatter本文は更新されていますが、このバージョンは旧本文に基づいています。\n\n旧バージョンは保持されますが、そのまま出力すると古い文が混在する可能性があります。このバージョンでEPUBを作成しますか？",
"剪贴板为空":"クリップボードが空です",
"剪贴板中没有可粘贴的书名。":"クリップボードに貼り付け可能な書名がありません。",
"EPUB 正在生成":"EPUBを生成中です",
"当前已有一个 EPUB 构建任务，请等待完成后再生成。":"EPUB構築タスクがすでに実行中です。完了後に再度生成してください。",
"请先完成 OCR 和格式处理":"先にOCRと整形処理を完了してください",
"翻译/发布前检查发现问题":"翻訳/公開前チェックで問題が見つかりました",
"旧正文快照已导出":"旧本文スナップショットを書き出しました",
"提取进行中":"抽出処理中",
"当前 PDF 正在提取。切换新书会安全丢弃旧任务结果。":"現在PDFを抽出中です。新しい本へ切り替えると古いタスク結果は安全に破棄されます。",
"请先选择 PDF 文件":"先にPDFファイルを選択してください",
"先确认当前结果":"先に現在の結果を確認してください",
"请先接受或拒绝当前 AI 结果，再开始下一次处理。":"現在のAI結果を採用または却下してから次の処理を開始してください。",
"AI修改":"AI変更",
"当前没有可见的 AI 文本修改。":"現在表示できるAIテキスト変更はありません。",
"尚未导入参考原文":"参照原文が未読込です",
"请先导入出版前草稿、Web版或校对稿。":"先に出版前草稿、Web版または校正稿を読み込んでください。",
"没有可评分版本":"評価できるバージョンがありません",
"请先载入 OCR、Formatter 或 AI 结果。":"先にOCR、FormatterまたはAI結果を読み込んでください。",
"缺少 OCR 版本":"OCRバージョンがありません",
"请先载入内置 OCR，并导入至少一份外部 OCR。":"先に内蔵OCRを読み込み、外部OCRを少なくとも1件読み込んでください。",
"无法生成融合稿":"融合稿を生成できません",
"请先载入内置 OCR，并导入/选择一份外部 OCR。":"先に内蔵OCRを読み込み、外部OCRを1件読み込み/選択してください。",
"没有融合报告":"融合レポートがありません",
"请先生成双 OCR 融合稿。":"先に2 OCR融合稿を生成してください。",
"请先确认 AI 结果":"先にAI結果を確認してください",
"当前仍有待确认的 AI 修改。请先逐项确认或拒绝，再运行发布修复。":"未確認のAI変更が残っています。項目ごとに確認または却下してから公開修復を実行してください。",
"没有可确定修复的问题":"決定論的に修復できる問題はありません",
"未发现能在不猜测原文的前提下自动修复的问题。其余项目需要人工或局部 AI 核对。":"原文を推測せず自動修復できる問題は見つかりませんでした。残りは手動または局所AI確認が必要です。",
"当前 AI 结果仍处于待确认状态。请先确认或拒绝，再把右侧作为可信正文套入版面。":"現在のAI結果はまだ確認待ちです。確認または却下してから右側を信頼本文としてレイアウトへ適用してください。",
"缺少 OCR 版面":"OCRレイアウトがありません",
"请先载入 OCR/页面管理文档，再套入右侧可信正文。":"先にOCR/ページ管理文書を読み込んでから右側の信頼本文を適用してください。",
"右侧正文过少":"右側本文が少なすぎます",
"右侧没有足够正文，已取消可信正文覆盖。":"右側に十分な本文がないため、信頼本文の置換を中止しました。",
"确认使用参考原文覆盖":"参照原文による置換を確認",
"当前右侧是参考/草稿文本。草稿可能与正式出版版存在作者增删改写。\n\n继续后，右侧文字将成为全部最终正文，旧 OCR 文字会彻底删除；OCR 只保留页码、目录和插图。是否继续？":"現在右側は参照/草稿テキストです。草稿は正式出版版と著者の追加・削除・改稿が異なる場合があります。\n\n続行すると右側テキストが最終本文全体となり、旧OCR本文は完全に削除されます。OCRにはページ番号・目次・挿絵だけが残ります。続行しますか？",
"参考原文不能直接写回":"参照原文は直接書き戻せません",
"出版前草稿只用于对照和裁决 AI 修改。正式出版版可能包含作者后续新增、删改和重排，不能用草稿全文覆盖 OCR/Formatter 结果。":"出版前草稿は比較とAI変更の裁決専用です。正式出版版には後の追加・削除・改稿・再配置が含まれる場合があるため、草稿全文でOCR/Formatter結果を置換できません。",
"当前 AI 结果仍处于待确认状态。请先查看修改，然后点击“确认AI结果（仅右侧）”或“接受并应用”。":"現在のAI結果はまだ確認待ちです。変更を確認し、「AI結果を確認（右側のみ）」または「受け入れて適用」をクリックしてください。",
"右侧没有可写回的文档版本":"右側に書き戻せる文書バージョンがありません",
"参考文件不存在":"参照ファイルが存在しません",
"术语表不存在":"用語集ファイルが存在しません",
"没有可载入结果":"読み込める結果がありません",
"请先在 OCR 识别页完成一次单模型 OCR。":"先にOCR認識画面で単一モデルOCRを1回実行してください。",
})

_EN.update({
"切换到单 OCR 结果":"Switch to Single-OCR Result",
"当前正在显示多模型 OCR 对比。切换后会暂存当前文本、对齐和人工选择，可用“返回多模型对比”完整恢复。继续吗？":"Multi-model OCR comparison is currently displayed. Switching will temporarily preserve the current text, alignment and manual choices; use “Return to Multi-model Comparison” to restore them fully. Continue?",
"没有单 OCR 结果":"No Single-OCR Result",
"请先点击“从 OCR 识别载入”。":"Click “Load from OCR” first.",
"请先刷新对齐":"Refresh Alignment First",
"源 OCR 已修改，请先点击“重新自动对齐”。":"The source OCR has changed. Click “Re-align Automatically” first.",
"没有该候选":"Candidate Not Available",
"当前融合候选中没有该模型的有效文字。":"The current fusion candidates contain no valid text from that model.",
"对齐行数已改变":"Aligned Row Count Changed",
"没有对比结果":"No Comparison Result",
"请先载入 2～6 份 OCR 结果。":"Load 2–6 OCR results first.",
"标准化检查完成":"Normalization Check Complete",
"当前各 OCR 结果与候选已使用统一 Unicode 码位，不需要修复。":"All current OCR results and candidates already use consistent Unicode code points; no repair is needed.",
"没有多模型结果":"No Multi-model Result",
"请先完成多模型 OCR。":"Complete multi-model OCR first.",
"请先重新对齐":"Re-align First",
"各 OCR 栏的行数已改变。请先点击“重新对齐”，再导出大模型对比包。":"OCR column row counts have changed. Click “Re-align” before exporting the LLM comparison package.",
"无法导出":"Cannot Export",
"当前 OCR 对齐状态不完整。":"The current OCR alignment state is incomplete.",
"请先完成多模型 OCR 并载入 OCR 对比。":"Complete multi-model OCR and load OCR comparison first.",
"当前已有逐源纠错或 AI 导入任务在后台执行。":"A per-source correction or AI import task is already running in the background.",
"无法准备 AI OCR 裁决包":"Cannot Prepare AI OCR Adjudication Package",
"当前 OCR 行数与对齐不一致，请先点击“重新对齐”。":"The OCR row count no longer matches the alignment. Click “Re-align” first.",
"替换当前 OCR 对比会话":"Replace Current OCR Comparison Session",
"恢复会替换当前 OCR 对比中的 2～6 份模型文档和候选状态，但不会重新 OCR。继续吗？":"Restoring will replace the 2–6 model documents and candidate state in the current OCR comparison, but will not run OCR again. Continue?",
"无法导入":"Cannot Import",
"选择出版参考 EPUB":"Choose Publication Reference EPUB",
"EPUB 电子书 (*.epub)":"EPUB eBook (*.epub)",
"请先载入与修复文件对应的多模型 OCR。":"Load the multi-model OCR corresponding to the repair file first.",
"当前已有 AI 或逐源纠错任务，请稍候。":"An AI or per-source correction task is already running. Please wait.",
"各 OCR 栏行数已改变。请先点击“重新对齐”。":"OCR column row counts have changed. Click “Re-align” first.",
"无法审定":"Cannot Adjudicate",
"没有结构底稿":"No Structure Draft",
"请先载入当前书的多模型 OCR 结果。":"Load the multi-model OCR result for the current book first.",
"正在导入":"Import in Progress",
"当前已有多模型 AI 或逐源纠错任务，请稍候。":"A multi-model AI or per-source correction task is already running. Please wait.",
"AI 审定融合稿已应用":"AI-adjudicated Fusion Draft Applied",
"多模型 AI 融合包已应用":"Multi-model AI Fusion Package Applied",
"没有结果":"No Result",
"请先运行多模型 OCR。":"Run multi-model OCR first.",
"单 OCR 结果已应用":"Single-OCR Result Applied",
"已重新对齐":"Re-aligned",
"源 OCR 的修改已经重新对齐并重建候选。请重新确认冲突句后再应用。":"Source-OCR changes were re-aligned and candidates rebuilt. Re-confirm conflicting sentences before applying.",
"仍有未选择候选":"Unselected Candidates Remain",
"当前图片不可用":"Current Image Unavailable",
"请先载入一条带原图的 OCR 句。":"Load an OCR sentence with its source image first.",
"仅支持 macOS":"macOS Only",
"苹果系统手写输入只在 macOS 上可用。":"Apple system handwriting input is available only on macOS.",
"没有校对稿":"No Proofreading Draft",
"请先完成 OCR。":"Complete OCR first.",
"请先停止当前 OCR 任务，再更新模型。运行中的 worker 不会被强制替换。":"Stop the current OCR task before updating models. Running workers will not be forcibly replaced.",
"请先检查":"Check First",
"请先点击“检查更新”，确认官方目标版本后再更新。":"Click “Check for Updates” and confirm the official target version before updating.",
"模型检查或更新正在进行，完成后才能关闭此窗口。":"Model checking or updating is in progress. This window can be closed after it finishes.",
"请先等待当前 OCR、排版、导出、模型或设备检测任务结束，再更新程序。":"Wait for current OCR, layout, export, model or device-detection tasks to finish before updating the application.",
"请先检查更新":"Check for Updates First",
"请先点击“检查 Git 更新”。":"Click “Check Git Update” first.",
"无需更新":"No Update Needed",
"程序更新进行中":"Application Update in Progress",
"请等待 Git 检查/更新完成后再关闭窗口，以免中断事务更新。":"Wait for Git checking/updating to finish before closing the window to avoid interrupting the transactional update.",
"多模型 OCR 结果无效":"Invalid Multi-model OCR Result",
"没有收到可用的多模型 OCR 文档。":"No usable multi-model OCR document was received.",
"扫描件优化完成":"Scan Cleanup Complete",
"当前模式不可用":"Current Mode Unavailable",
"系统凭据库不可用":"System Credential Store Unavailable",
"当前平台不提供本程序支持的系统级凭据存储。请使用 PADDLEOCR_ACCESS_TOKEN 环境变量（兼容 AISTUDIO_ACCESS_TOKEN）；程序不会退回明文保存。":"This platform does not provide a supported system credential store. Use the PADDLEOCR_ACCESS_TOKEN environment variable (AISTUDIO_ACCESS_TOKEN is also supported); the application will not fall back to plaintext storage.",
"载入失败":"Load Failed",
"断点目录":"Checkpoint Folder",
"导入失败":"Import Failed",
"缺少 API Key":"API Key Missing",
"请先输入 API Key，再刷新模型列表。":"Enter an API Key before refreshing the model list.",
"缺少 Base URL":"Base URL Missing",
"自定义接口需要先填写 Base URL。":"A custom provider requires a Base URL first.",
"严格覆盖未通过":"Strict Replacement Failed",
"无法开始 AI 处理":"Cannot Start AI Processing",
"可信正文完整性校验失败":"Trusted-text Integrity Check Failed",
"结果目录不可用":"Result Folder Unavailable",
"没有 OCR 结果":"No OCR Result",
"请先从 OCR 识别载入单 OCR 结果。":"Load a single-OCR result from OCR Recognition first.",
"当前单 OCR 已使用统一 Unicode 码位，不需要修复。":"The current single-OCR result already uses consistent Unicode code points; no repair is needed.",
"尚未选择 EPUB":"No EPUB Selected",
"请先选择出版参考 EPUB，或取消勾选该选项。":"Choose a publication reference EPUB first, or disable that option.",
"请先从 OCR 识别载入结果。":"Load a result from OCR Recognition first.",
"苹果手写面板暂不可用":"Apple Handwriting Panel Temporarily Unavailable",
"保存失败":"Save Failed",
"当前句在校对文档中不存在。":"The current sentence does not exist in the proofreading document.",
"读取失败":"Read Failed",
"加载失败":"Load Failed",
"未检测到竖列":"No Vertical Columns Detected",
"当前固定区域没有检测到稳定竖列。请重新框选纯正文区域，或提高分列灵敏度。":"No stable vertical columns were detected in the fixed region. Select a body-only region again or increase column sensitivity.",
"人工纠错不可用":"Manual Correction Unavailable",
"API Key 无效":"Invalid API Key",
"Apple 手写识别":"Apple Handwriting Recognition",
"Apple PKStrokeRecognizer Swift 桥接已编译，日语支持检测通过。":"The Apple PKStrokeRecognizer Swift bridge compiled successfully and Japanese support passed detection.",
"选择文字颜色":"Choose Text Color",
"选择背景颜色":"Choose Background Color",
})

_JA.update({
"切换到单 OCR 结果":"単一OCR結果へ切り替え",
"当前正在显示多模型 OCR 对比。切换后会暂存当前文本、对齐和人工选择，可用“返回多模型对比”完整恢复。继续吗？":"現在は複数モデルOCR比較を表示しています。切り替えると現在のテキスト・整列・手動選択を一時保存し、「複数モデル比較へ戻る」で完全復元できます。続行しますか？",
"没有单 OCR 结果":"単一OCR結果がありません",
"请先点击“从 OCR 识别载入”。":"先に「OCR認識から読み込む」をクリックしてください。",
"请先刷新对齐":"先に整列を更新してください",
"源 OCR 已修改，请先点击“重新自动对齐”。":"元OCRが変更されています。先に「自動再整列」をクリックしてください。",
"没有该候选":"該当候補がありません",
"当前融合候选中没有该模型的有效文字。":"現在の融合候補にそのモデルの有効テキストがありません。",
"对齐行数已改变":"整列行数が変更されました",
"没有对比结果":"比較結果がありません",
"请先载入 2～6 份 OCR 结果。":"先に2～6件のOCR結果を読み込んでください。",
"标准化检查完成":"正規化チェック完了",
"当前各 OCR 结果与候选已使用统一 Unicode 码位，不需要修复。":"現在のOCR結果と候補はすでに統一されたUnicodeコードポイントを使用しているため修復不要です。",
"没有多模型结果":"複数モデル結果がありません",
"请先完成多模型 OCR。":"先に複数モデルOCRを完了してください。",
"请先重新对齐":"先に再整列してください",
"各 OCR 栏的行数已改变。请先点击“重新对齐”，再导出大模型对比包。":"各OCR欄の行数が変わっています。「再整列」をクリックしてからLLM比較パッケージを書き出してください。",
"无法导出":"書き出せません",
"当前 OCR 对齐状态不完整。":"現在のOCR整列状態が不完全です。",
"请先完成多模型 OCR 并载入 OCR 对比。":"先に複数モデルOCRを完了し、OCR比較を読み込んでください。",
"当前已有逐源纠错或 AI 导入任务在后台执行。":"ソース別修正またはAI読み込みタスクがすでにバックグラウンドで実行中です。",
"无法准备 AI OCR 裁决包":"AI OCR裁決パッケージを準備できません",
"当前 OCR 行数与对齐不一致，请先点击“重新对齐”。":"現在のOCR行数と整列が一致していません。先に「再整列」をクリックしてください。",
"替换当前 OCR 对比会话":"現在のOCR比較セッションを置換",
"恢复会替换当前 OCR 对比中的 2～6 份模型文档和候选状态，但不会重新 OCR。继续吗？":"復元すると現在のOCR比較内の2～6件のモデル文書と候補状態を置き換えますが、OCRは再実行しません。続行しますか？",
"无法导入":"読み込めません",
"选择出版参考 EPUB":"出版参照EPUBを選択",
"EPUB 电子书 (*.epub)":"EPUB電子書籍 (*.epub)",
"请先载入与修复文件对应的多模型 OCR。":"先に修復ファイルに対応する複数モデルOCRを読み込んでください。",
"当前已有 AI 或逐源纠错任务，请稍候。":"AIまたはソース別修正タスクが実行中です。お待ちください。",
"各 OCR 栏行数已改变。请先点击“重新对齐”。":"各OCR欄の行数が変わっています。先に「再整列」をクリックしてください。",
"无法审定":"裁決できません",
"没有结构底稿":"構造下書きがありません",
"请先载入当前书的多模型 OCR 结果。":"先に現在の本の複数モデルOCR結果を読み込んでください。",
"正在导入":"読み込み中",
"当前已有多模型 AI 或逐源纠错任务，请稍候。":"複数モデルAIまたはソース別修正タスクが実行中です。お待ちください。",
"AI 审定融合稿已应用":"AI裁決済み融合稿を適用しました",
"多模型 AI 融合包已应用":"複数モデルAI融合パッケージを適用しました",
"没有结果":"結果がありません",
"请先运行多模型 OCR。":"先に複数モデルOCRを実行してください。",
"单 OCR 结果已应用":"単一OCR結果を適用しました",
"已重新对齐":"再整列しました",
"源 OCR 的修改已经重新对齐并重建候选。请重新确认冲突句后再应用。":"元OCRの変更を再整列して候補を再構築しました。競合文を再確認してから適用してください。",
"仍有未选择候选":"未選択候補が残っています",
"当前图片不可用":"現在の画像を利用できません",
"请先载入一条带原图的 OCR 句。":"先に元画像付きのOCR文を読み込んでください。",
"仅支持 macOS":"macOSのみ対応",
"苹果系统手写输入只在 macOS 上可用。":"Appleシステム手書き入力はmacOSでのみ利用できます。",
"没有校对稿":"校正稿がありません",
"请先完成 OCR。":"先にOCRを完了してください。",
"请先停止当前 OCR 任务，再更新模型。运行中的 worker 不会被强制替换。":"モデル更新前に現在のOCRタスクを停止してください。実行中workerを強制置換しません。",
"请先检查":"先に確認してください",
"请先点击“检查更新”，确认官方目标版本后再更新。":"先に「更新を確認」をクリックし、公式の対象バージョンを確認してから更新してください。",
"模型检查或更新正在进行，完成后才能关闭此窗口。":"モデル確認または更新中です。完了後にこのウィンドウを閉じられます。",
"请先等待当前 OCR、排版、导出、模型或设备检测任务结束，再更新程序。":"現在のOCR・組版・書き出し・モデル・デバイス検出タスクが終了してからアプリを更新してください。",
"请先检查更新":"先に更新を確認してください",
"请先点击“检查 Git 更新”。":"先に「Git更新を確認」をクリックしてください。",
"无需更新":"更新不要",
"程序更新进行中":"アプリ更新中",
"请等待 Git 检查/更新完成后再关闭窗口，以免中断事务更新。":"トランザクション更新を中断しないよう、Git確認/更新完了後にウィンドウを閉じてください。",
"多模型 OCR 结果无效":"複数モデルOCR結果が無効です",
"没有收到可用的多模型 OCR 文档。":"利用可能な複数モデルOCR文書を受信できませんでした。",
"扫描件优化完成":"スキャン最適化完了",
"当前模式不可用":"現在のモードは利用できません",
"系统凭据库不可用":"システム資格情報ストアを利用できません",
"当前平台不提供本程序支持的系统级凭据存储。请使用 PADDLEOCR_ACCESS_TOKEN 环境变量（兼容 AISTUDIO_ACCESS_TOKEN）；程序不会退回明文保存。":"現在のプラットフォームには対応するシステム資格情報ストアがありません。PADDLEOCR_ACCESS_TOKEN環境変数（AISTUDIO_ACCESS_TOKEN互換）を使用してください。平文保存にはフォールバックしません。",
"载入失败":"読み込み失敗",
"断点目录":"チェックポイントフォルダ",
"导入失败":"インポート失敗",
"缺少 API Key":"API Keyがありません",
"请先输入 API Key，再刷新模型列表。":"API Keyを入力してからモデル一覧を更新してください。",
"缺少 Base URL":"Base URLがありません",
"自定义接口需要先填写 Base URL。":"カスタムAPIでは先にBase URLを入力してください。",
"严格覆盖未通过":"厳密置換に失敗しました",
"无法开始 AI 处理":"AI処理を開始できません",
"可信正文完整性校验失败":"信頼本文の整合性検証に失敗しました",
"结果目录不可用":"結果フォルダを利用できません",
"没有 OCR 结果":"OCR結果がありません",
"请先从 OCR 识别载入单 OCR 结果。":"先にOCR認識から単一OCR結果を読み込んでください。",
"当前单 OCR 已使用统一 Unicode 码位，不需要修复。":"現在の単一OCRは統一Unicodeコードポイントを使用しているため修復不要です。",
"尚未选择 EPUB":"EPUBが選択されていません",
"请先选择出版参考 EPUB，或取消勾选该选项。":"先に出版参照EPUBを選択するか、そのオプションをオフにしてください。",
"请先从 OCR 识别载入结果。":"先にOCR認識から結果を読み込んでください。",
"苹果手写面板暂不可用":"Apple手書きパネルは現在利用できません",
"保存失败":"保存失敗",
"当前句在校对文档中不存在。":"現在の文は校正文書に存在しません。",
"读取失败":"読み取り失敗",
"加载失败":"読み込み失敗",
"未检测到竖列":"縦列を検出できません",
"当前固定区域没有检测到稳定竖列。请重新框选纯正文区域，或提高分列灵敏度。":"現在の固定領域で安定した縦列を検出できません。本文のみの領域を再選択するか、列分割感度を上げてください。",
"人工纠错不可用":"手動修正を利用できません",
"API Key 无效":"API Keyが無効です",
"Apple 手写识别":"Apple手書き認識",
"Apple PKStrokeRecognizer Swift 桥接已编译，日语支持检测通过。":"Apple PKStrokeRecognizer Swiftブリッジのコンパイルと日本語対応検出に成功しました。",
"选择文字颜色":"文字色を選択",
"选择背景颜色":"背景色を選択",
})

# Formatter's save filter is assembled at runtime rather than as a GUI literal.
_EN["Word 文档 (*.docx);;JSON 数据 (*.json);;Markdown 文本 (*.md);;纯文本 (*.txt)"] = "Word Document (*.docx);;JSON Data (*.json);;Markdown Text (*.md);;Plain Text (*.txt)"
_JA["Word 文档 (*.docx);;JSON 数据 (*.json);;Markdown 文本 (*.md);;纯文本 (*.txt)"] = "Word文書 (*.docx);;JSONデータ (*.json);;Markdownテキスト (*.md);;プレーンテキスト (*.txt)"
_EN["预览失败"] = "Preview Failed"
_JA["预览失败"] = "プレビュー失敗"



_EN.update({
    "仍有空列未输入": "Empty Columns Still Need Input",
    "无法应用复核结果": "Cannot Apply Review Results",
    "确认清空": "Confirm Clear",
    "清空失败": "Clear Failed",
    "继续后会保留醒目的 □ 标记，不会静默删除这些列；建议返回逐列补全。": "Continuing will keep conspicuous □ markers and will not silently delete these columns; returning to complete them column by column is recommended.",
    "仍要应用当前结果吗？": "Apply the current result anyway?",
    "磁盘上的原始文件不会被删除。": "Original files on disk will not be deleted.",
})
_JA.update({
    "仍有空列未输入": "未入力の空列が残っています",
    "无法应用复核结果": "確認結果を適用できません",
    "确认清空": "クリアの確認",
    "清空失败": "クリア失敗",
    "继续后会保留醒目的 □ 标记，不会静默删除这些列；建议返回逐列补全。": "続行すると目立つ □ マークを保持し、これらの列を黙って削除しません。戻って列ごとに補完することを推奨します。",
    "仍要应用当前结果吗？": "それでも現在の結果を適用しますか？",
    "磁盘上的原始文件不会被删除。": "ディスク上の元ファイルは削除されません。",
})

# Anchored templates for runtime-composed dialog lines.  These are intentionally
# narrower than general UI patterns: every capture is copied verbatim so paths,
# model labels, user profile names and diagnostic values can never be translated
# accidentally.
def _tr_list(value: str, language: str) -> str:
    return "、".join(translate_text(part, language) for part in value.split("、"))


_DIALOG_LINE_PATTERNS = {
    LANG_EN: [
        (re.compile(r"还有 (\d+) 列 OCR 三次均为空，尚未人工输入。"), lambda m: f"{m.group(1)} column(s) are still empty after three OCR attempts and have not been entered manually."),
        (re.compile(r"确定清空当前(.*)工作区？"), lambda m: f"Clear the current {translate_text(m.group(1), LANG_EN)} workspace?"),
        (re.compile(r"(.*)工作区未能完全清空，请查看终端日志。"), lambda m: f"The {translate_text(m.group(1), LANG_EN)} workspace could not be fully cleared. Check the terminal log."),
        (re.compile(r"确定要从当前导入中移除选中的 (\d+) 页吗？"), lambda m: f"Remove the selected {m.group(1)} page(s) from this import?"),
        (re.compile(r"（只是从这次处理里去掉，不会删除原始图片文件）"), lambda m: "(They are removed only from this run; the original image files are not deleted.)"),
        (re.compile(r"(.+) 已经执行过：(.+)"), lambda m: f"{translate_text(m.group(1), LANG_EN)} has already run: {_tr_list(m.group(2), LANG_EN)}"),
        (re.compile(r"从 DOCX 导入 (\d+) 个块，(\d+) 个章节"), lambda m: f"Imported {m.group(1)} blocks and {m.group(2)} chapters from DOCX"),
        (re.compile(r"从 EPUB 导入 (\d+) 个块，(\d+) 个目录条目"), lambda m: f"Imported {m.group(1)} blocks and {m.group(2)} TOC entries from EPUB"),
        (re.compile(r"已导入 (\d+) 个块"), lambda m: f"Imported {m.group(1)} blocks"),
        (re.compile(r"已应用手动编辑：(\d+) 个文本块"), lambda m: f"Applied manual edits to {m.group(1)} text blocks"),
        (re.compile(r"已保存[:：](.*)"), lambda m: f"Saved:{m.group(1)}"),
        (re.compile(r"已保存到：(.*)"), lambda m: f"Saved to:{m.group(1)}"),
        (re.compile(r"已导出:\s*(.*)"), lambda m: f"Exported: {m.group(1)}"),
        (re.compile(r"已导入格式「(.*)」"), lambda m: f"Imported format “{m.group(1)}”"),
        (re.compile(r"确定删除格式「(.*)」？此操作不可撤销。"), lambda m: f"Delete format “{m.group(1)}”? This cannot be undone."),
        (re.compile(r"确定清空「(.*)」？其他两个版本不会受影响。"), lambda m: f"Clear “{m.group(1)}”? The other two versions will not be affected."),
        (re.compile(r"确定删除本书全部 AI 断点？"), lambda m: "Delete all AI checkpoints for this book?"),
        (re.compile(r"EPUB 已生成:"), lambda m: "EPUB generated:"),
        (re.compile(r"发现 (\d+) 个已删除或不存在的输入，已从本次 OCR 队列移除："), lambda m: f"Removed {m.group(1)} deleted or missing input(s) from this OCR queue:"),
        (re.compile(r"当前“(.*)”模式不能使用：(.*)"), lambda m: f"The “{m.group(1)}” mode cannot use: {_tr_list(m.group(2), LANG_EN)}"),
        (re.compile(r"(.+)文本行数和文档文本块数不一致：(\d+) 行 / (\d+) 块。"), lambda m: f"{m.group(1)} text has {m.group(2)} lines but the document has {m.group(3)} structured blocks."),
        (re.compile(r"当前编辑内容包含 (\d+) 个非空文本段，而版本含 (\d+) 个结构化正文块。"), lambda m: f"The current edit contains {m.group(1)} non-empty text segments, while the version contains {m.group(2)} structured body blocks."),
        (re.compile(r"请先载入或生成(.+)"), lambda m: f"Load or generate {translate_text(m.group(1), LANG_EN)} first"),
        (re.compile(r"已保存 (.+) 版本到项目目录"), lambda m: f"Saved the {m.group(1)} version to the project folder"),
        (re.compile(r"右侧 (\d+) 字，输出 (\d+) 字。"), lambda m: f"Right side: {m.group(1)} chars; output: {m.group(2)} chars."),
        (re.compile(r"还有 (\d+) 句没有打钩选择。已跳到第一处；选择后其他候选会消失且不留空行。"), lambda m: f"{m.group(1)} sentence(s) still have no selected candidate. Jumped to the first; after selection, other candidates will disappear without leaving blank lines."),
        (re.compile(r"导入完成：(\d+) 个内容块，已同步到后续工作区。"), lambda m: f"Import complete: {m.group(1)} content blocks synchronized to downstream workspaces."),
        (re.compile(r"已将校对稿送入后续工作流。"), lambda m: "The proofreading draft has been sent to downstream workflows."),
        (re.compile(r"核对 (\d+) 句，修改 (\d+) 句。"), lambda m: f"Reviewed {m.group(1)} sentence(s); changed {m.group(2)}."),
        (re.compile(r"确认(.+)"), lambda m: f"Confirm {translate_text(m.group(1), LANG_EN)}"),
        (re.compile(r"模型：(.*)"), lambda m: f"Model: {m.group(1)}"),
        (re.compile(r"本地版本：(.*)"), lambda m: f"Local version: {m.group(1)}"),
        (re.compile(r"目标版本：(.*)"), lambda m: f"Target version: {m.group(1)}"),
        (re.compile(r"程序源码已安全更新到 v([^。]+)。(.*)"), lambda m: f"Application source was safely updated to v{m.group(1)}. {m.group(2)}"),
        (re.compile(r"Apple PKStrokeRecognizer 当前不可用。若要安装兼容备用，请在程序目录运行："), lambda m: "Apple PKStrokeRecognizer is currently unavailable. To install the compatible fallback, run this in the application folder:"),
        (re.compile(r"当前状态：(.*)"), lambda m: f"Current status: {m.group(1)}"),
        (re.compile(r"当前对齐为 (\d+) 行；各 OCR 栏现在为：(.*)。"), lambda m: f"Current alignment has {m.group(1)} rows; OCR columns now have: {m.group(2)}."),
        (re.compile(r"假冲突减少：(\d+) 句"), lambda m: f"False conflicts reduced by {m.group(1)} sentence(s)"),
        (re.compile(r"正文无损修复 (\d+) 个文本单元、(\d+) 处；仅比较处理 (\d+) 处。"), lambda m: f"Losslessly repaired {m.group(1)} text units / {m.group(2)} changes; comparison-only handling: {m.group(3)}."),
        (re.compile(r"删除 OCR 字符：0；汉字/异体字替换：0。"), lambda m: "Deleted OCR characters: 0; kanji/variant substitutions: 0."),
        (re.compile(r"已优化 (\d+) 个源页面，当前共 (\d+) 页。"), lambda m: f"Optimized {m.group(1)} source page(s); current total: {m.group(2)} page(s)."),
        (re.compile(r"拆分双页 (\d+) 张"), lambda m: f"split {m.group(1)} spread(s)"),
        (re.compile(r"几何校正 (\d+) 页"), lambda m: f"geometry corrected {m.group(1)} page(s)"),
        (re.compile(r"漂白/去阴影 (\d+) 页"), lambda m: f"whitened/removed shadows on {m.group(1)} page(s)"),
        (re.compile(r"原图未修改，可点击“恢复优化前”回退。"), lambda m: "Source images were not modified; click “Restore Before Optimization” to revert."),
        (re.compile(r"读取修改：(\d+) 条"), lambda m: f"Read updates: {m.group(1)}"),
        (re.compile(r"已选择：(\d+) 条"), lambda m: f"Selected: {m.group(1)}"),
        (re.compile(r"待人工：(\d+) 条"), lambda m: f"Needs manual review: {m.group(1)}"),
        (re.compile(r"原子事务：(\d+) 组"), lambda m: f"Atomic transactions: {m.group(1)}"),
        (re.compile(r"过期冲突：(\d+) 条"), lambda m: f"Stale conflicts: {m.group(1)}"),
        (re.compile(r"三方合并：(\d+) 条"), lambda m: f"Three-way merges: {m.group(1)}"),
        (re.compile(r"已修复 (\d+) 处相邻错位，涉及 (\d+) 行。"), lambda m: f"Repaired {m.group(1)} adjacent misalignment(s) affecting {m.group(2)} row(s)."),
        (re.compile(r"仍有 (\d+) 个单模型空白单元需要复核。"), lambda m: f"{m.group(1)} single-model blank cell(s) still need review."),
        (re.compile(r"用户已修改的 edited_text 保留 (\d+) 行。"), lambda m: f"Preserved {m.group(1)} row(s) of user-edited edited_text."),
        (re.compile(r"输出：(.*)"), lambda m: f"Output: {m.group(1)}"),
    ],
    LANG_JA: [
        (re.compile(r"还有 (\d+) 列 OCR 三次均为空，尚未人工输入。"), lambda m: f"{m.group(1)} 列が3回OCRしても空のままで、まだ手動入力されていません。"),
        (re.compile(r"确定清空当前(.*)工作区？"), lambda m: f"現在の{translate_text(m.group(1), LANG_JA)}ワークスペースをクリアしますか？"),
        (re.compile(r"(.*)工作区未能完全清空，请查看终端日志。"), lambda m: f"{translate_text(m.group(1), LANG_JA)}ワークスペースを完全にクリアできませんでした。ターミナルログを確認してください。"),
        (re.compile(r"确定要从当前导入中移除选中的 (\d+) 页吗？"), lambda m: f"現在の読み込みから選択した {m.group(1)} ページを外しますか？"),
        (re.compile(r"（只是从这次处理里去掉，不会删除原始图片文件）"), lambda m: "（今回の処理対象から外すだけで、元画像ファイルは削除しません）"),
        (re.compile(r"(.+) 已经执行过：(.+)"), lambda m: f"{translate_text(m.group(1), LANG_JA)} は実行済みです：{_tr_list(m.group(2), LANG_JA)}"),
        (re.compile(r"从 DOCX 导入 (\d+) 个块，(\d+) 个章节"), lambda m: f"DOCXから {m.group(1)} ブロック、{m.group(2)} 章を読み込みました"),
        (re.compile(r"从 EPUB 导入 (\d+) 个块，(\d+) 个目录条目"), lambda m: f"EPUBから {m.group(1)} ブロック、目次 {m.group(2)} 件を読み込みました"),
        (re.compile(r"已导入 (\d+) 个块"), lambda m: f"{m.group(1)} ブロックを読み込みました"),
        (re.compile(r"已应用手动编辑：(\d+) 个文本块"), lambda m: f"手動編集を {m.group(1)} テキストブロックに適用しました"),
        (re.compile(r"已保存[:：](.*)"), lambda m: f"保存しました：{m.group(1)}"),
        (re.compile(r"已保存到：(.*)"), lambda m: f"保存先：{m.group(1)}"),
        (re.compile(r"已导出:\s*(.*)"), lambda m: f"書き出しました：{m.group(1)}"),
        (re.compile(r"已导入格式「(.*)」"), lambda m: f"形式「{m.group(1)}」を読み込みました"),
        (re.compile(r"确定删除格式「(.*)」？此操作不可撤销。"), lambda m: f"形式「{m.group(1)}」を削除しますか？この操作は取り消せません。"),
        (re.compile(r"确定清空「(.*)」？其他两个版本不会受影响。"), lambda m: f"「{m.group(1)}」をクリアしますか？他の2バージョンには影響しません。"),
        (re.compile(r"确定删除本书全部 AI 断点？"), lambda m: "この本のAIチェックポイントをすべて削除しますか？"),
        (re.compile(r"EPUB 已生成:"), lambda m: "EPUBを生成しました："),
        (re.compile(r"发现 (\d+) 个已删除或不存在的输入，已从本次 OCR 队列移除："), lambda m: f"削除済みまたは存在しない入力 {m.group(1)} 件を今回のOCRキューから除外しました："),
        (re.compile(r"当前“(.*)”模式不能使用：(.*)"), lambda m: f"現在の「{m.group(1)}」モードでは使用できません：{_tr_list(m.group(2), LANG_JA)}"),
        (re.compile(r"(.+)文本行数和文档文本块数不一致：(\d+) 行 / (\d+) 块。"), lambda m: f"{m.group(1)}テキストは {m.group(2)} 行ですが、文書には {m.group(3)} 構造化ブロックがあります。"),
        (re.compile(r"当前编辑内容包含 (\d+) 个非空文本段，而版本含 (\d+) 个结构化正文块。"), lambda m: f"現在の編集内容には非空テキスト段落が {m.group(1)} 件ありますが、バージョンには構造化本文ブロックが {m.group(2)} 件あります。"),
        (re.compile(r"请先载入或生成(.+)"), lambda m: f"先に{translate_text(m.group(1), LANG_JA)}を読み込むか生成してください"),
        (re.compile(r"已保存 (.+) 版本到项目目录"), lambda m: f"{m.group(1)} バージョンをプロジェクトフォルダに保存しました"),
        (re.compile(r"右侧 (\d+) 字，输出 (\d+) 字。"), lambda m: f"右側：{m.group(1)} 文字、出力：{m.group(2)} 文字。"),
        (re.compile(r"还有 (\d+) 句没有打钩选择。已跳到第一处；选择后其他候选会消失且不留空行。"), lambda m: f"まだ {m.group(1)} 文で候補が選択されていません。最初の箇所へ移動しました。選択すると他候補は消え、空行は残りません。"),
        (re.compile(r"导入完成：(\d+) 个内容块，已同步到后续工作区。"), lambda m: f"読み込み完了：{m.group(1)} コンテンツブロックを後続ワークスペースへ同期しました。"),
        (re.compile(r"已将校对稿送入后续工作流。"), lambda m: "校正稿を後続ワークフローへ送りました。"),
        (re.compile(r"核对 (\d+) 句，修改 (\d+) 句。"), lambda m: f"{m.group(1)} 文を確認し、{m.group(2)} 文を修正しました。"),
        (re.compile(r"确认(.+)"), lambda m: f"{translate_text(m.group(1), LANG_JA)}を確認"),
        (re.compile(r"模型：(.*)"), lambda m: f"モデル：{m.group(1)}"),
        (re.compile(r"本地版本：(.*)"), lambda m: f"ローカル版：{m.group(1)}"),
        (re.compile(r"目标版本：(.*)"), lambda m: f"対象版：{m.group(1)}"),
        (re.compile(r"程序源码已安全更新到 v([^。]+)。(.*)"), lambda m: f"アプリのソースを安全に v{m.group(1)} へ更新しました。{m.group(2)}"),
        (re.compile(r"Apple PKStrokeRecognizer 当前不可用。若要安装兼容备用，请在程序目录运行："), lambda m: "Apple PKStrokeRecognizerは現在利用できません。互換フォールバックをインストールするにはアプリフォルダで次を実行してください："),
        (re.compile(r"当前状态：(.*)"), lambda m: f"現在の状態：{m.group(1)}"),
        (re.compile(r"当前对齐为 (\d+) 行；各 OCR 栏现在为：(.*)。"), lambda m: f"現在の整列は {m.group(1)} 行です。各OCR欄：{m.group(2)}。"),
        (re.compile(r"假冲突减少：(\d+) 句"), lambda m: f"疑似競合を {m.group(1)} 文削減"),
        (re.compile(r"正文无损修复 (\d+) 个文本单元、(\d+) 处；仅比较处理 (\d+) 处。"), lambda m: f"本文を {m.group(1)} テキスト単位・{m.group(2)} 箇所で無損失修復；比較専用処理は {m.group(3)} 箇所。"),
        (re.compile(r"删除 OCR 字符：0；汉字/异体字替换：0。"), lambda m: "OCR文字削除：0、漢字/異体字置換：0。"),
        (re.compile(r"已优化 (\d+) 个源页面，当前共 (\d+) 页。"), lambda m: f"元ページ {m.group(1)} 件を最適化し、現在は全 {m.group(2)} ページです。"),
        (re.compile(r"拆分双页 (\d+) 张"), lambda m: f"見開き分割 {m.group(1)} 件"),
        (re.compile(r"几何校正 (\d+) 页"), lambda m: f"形状補正 {m.group(1)} ページ"),
        (re.compile(r"漂白/去阴影 (\d+) 页"), lambda m: f"白地化/影除去 {m.group(1)} ページ"),
        (re.compile(r"原图未修改，可点击“恢复优化前”回退。"), lambda m: "元画像は変更していません。「最適化前に戻す」で復元できます。"),
        (re.compile(r"读取修改：(\d+) 条"), lambda m: f"読み取った変更：{m.group(1)} 件"),
        (re.compile(r"已选择：(\d+) 条"), lambda m: f"選択済み：{m.group(1)} 件"),
        (re.compile(r"待人工：(\d+) 条"), lambda m: f"手動確認待ち：{m.group(1)} 件"),
        (re.compile(r"原子事务：(\d+) 组"), lambda m: f"原子トランザクション：{m.group(1)} 組"),
        (re.compile(r"过期冲突：(\d+) 条"), lambda m: f"期限切れ競合：{m.group(1)} 件"),
        (re.compile(r"三方合并：(\d+) 条"), lambda m: f"3-wayマージ：{m.group(1)} 件"),
        (re.compile(r"已修复 (\d+) 处相邻错位，涉及 (\d+) 行。"), lambda m: f"隣接ずれ {m.group(1)} 箇所（{m.group(2)} 行）を修復しました。"),
        (re.compile(r"仍有 (\d+) 个单模型空白单元需要复核。"), lambda m: f"単一モデル空白セル {m.group(1)} 件がまだ要確認です。"),
        (re.compile(r"用户已修改的 edited_text 保留 (\d+) 行。"), lambda m: f"ユーザー編集済み edited_text を {m.group(1)} 行保持しました。"),
        (re.compile(r"输出：(.*)"), lambda m: f"出力：{m.group(1)}"),
    ],
}

# Deep-audit additions: stable lines used inside runtime-composed reports.  Keep
# these as exact UI sentences so arbitrary paths, exception messages, OCR text
# and model output continue to pass through untouched.
_EN.update({
    "继续会基于当前文档再次执行，可能改变已有结果。": "Continuing will run again from the current document and may change existing results.",
    "如果想从处理前重新开始，请先使用「清空处理后」或「重新载入处理前」。": "To restart from the pre-processing state, use “Clear After” or “Reload Before” first.",
    "是否继续？": "Continue?",
    "继续吗？": "Continue?",
    "可直接勾选步骤运行后处理。": "You can select steps and run post-processing directly.",
    "勾选「前后书剥离」等步骤运行后处理，可清理残留的样板文字。": "Select steps such as “Remove Front/Back Matter” and run post-processing to clean remaining boilerplate text.",
    "请保持一行对应一个文本块；删除空行可以，但不要合并或拆分块。": "Keep one line per text block. Blank lines may be removed, but do not merge or split blocks.",
    "AI 排版结果中的 block 内部换行不会影响 EPUB；但手动改变段落数量时，无法安全映射回原结构。请撤销段落合并/拆分，或重新执行 AI 纠错排版。": "Line breaks inside an AI-layout block do not affect the EPUB, but manually changing the paragraph count cannot be mapped safely back to the original structure. Undo paragraph merges/splits or run AI correction/layout again.",
    "仍可手动填写模型名称。": "You can still enter the model name manually.",
    "建议在“查看AI修改”中取消勾选并保留原文。仍要继续吗？": "It is recommended to uncheck these changes in “View AI Changes” and keep the original text. Continue anyway?",
    "当前结果已同步 Formatter/EPUB；原 OCR、外部 OCR、AI 和参考原文版本仍独立保留。": "The current result has been synchronized to Formatter/EPUB; the original OCR, external OCR, AI and reference-source versions remain independent.",
    "只修改 edited_text 或 Markdown 校对结果区，不要改动 ID 和结构清单。": "Edit only edited_text or the Markdown proofreading result section; do not change IDs or the structure manifest.",
    "交给大模型时只修改 edited_text 或 Markdown 的“大模型校对结果”区域。": "When sending this to an LLM, edit only edited_text or the “LLM proofreading result” section in Markdown.",
    "大模型可在 editable_conflict.model_edits 中只修正错误模型，也可选填 ai_verdict.final_text 作为最终融合裁决；上一轮 accepted 结果在新包中只作为参考，可由后续 AI 提交更好的 final_text：": "The LLM may correct only erroneous models in editable_conflict.model_edits, or optionally provide ai_verdict.final_text as the final fusion decision. Previously accepted results are references only in the new package and may be replaced by a better final_text in a later AI pass:",
    "已直接恢复 OCR 文字、物理列、候选和人工选择，没有重新运行 OCR。": "OCR text, physical columns, candidates and manual selections were restored directly without rerunning OCR.",
    "AI 结果按稳定列 ID 累积合并；后续已接受结果可替换同句旧 AI，未决结果不会反向清空。NDLOCR、48px、Apple Vision 等原文和原分歧始终保留。": "AI results are accumulated by stable column ID. Later accepted results may replace older AI results for the same sentence, while unresolved results never clear prior decisions. Original NDLOCR, 48px, Apple Vision text and original disagreements are always preserved.",
    "已包含锁定 Ruby sidecar、AI 正文模板、最终 EPUB 构建器和 Ruby 验证器。": "Includes the locked Ruby sidecar, AI body template, final EPUB builder and Ruby validator.",
    "融合 JSON 和稳定 ID 骨架 EPUB 已打包：": "The fusion JSON and stable-ID skeleton EPUB were packaged:",
    "原子事务在任一成员上选择/撤销时会整组同步；确认后再点击“应用融合稿”。": "Selecting or clearing any member of an atomic transaction synchronizes the entire group. Confirm the result before clicking “Apply Fusion Draft”.",
    "允许新增或删除换行，请点击“重新自动对齐”后再继续。": "Line breaks may be added or removed; click “Re-align Automatically” before continuing.",
    "本操作只在本次确认后执行。更新会先下载和校验，再替换模型；NDLOCR-Lite 与 48px AR 会保留一个本地回退备份。": "This operation runs only after this confirmation. The update is downloaded and verified before replacement; NDLOCR-Lite and 48px AR keep one local rollback backup.",
    "不会更新 OCR 模型，也不会删除虚拟环境、模型缓存、书籍、输出和日志。更新完成后需要重启程序。": "OCR models will not be updated, and virtual environments, model caches, books, outputs and logs will not be deleted. Restart the application after the update.",
    "请关闭并重新启动 Novel Formatter。": "Close and restart Novel Formatter.",
    "构建期间当前正文已经切换，因此未把旧包预览安装到新书工作区。": "The active body text changed during the build, so the old package preview was not installed into the new-book workspace.",
    "文本框已获得焦点，仍可从 macOS 输入菜单切换到日语输入法或系统手写输入。": "The text box has focus. You can still switch to a Japanese input method or system handwriting from the macOS Input menu.",
    "人工纠错工作台未能打开，将继续使用完整的普通 OCR 底稿。": "The manual correction workbench could not be opened; the complete normal OCR draft will continue to be used.",
    "请先重新对齐": "Re-align First",
    "原始多模型对齐：保持不变": "Original multi-model alignment: unchanged",
    "原始 OCR 实际回写：0 列 / 0 模型行": "Original OCR actually written back: 0 columns / 0 model rows",
    "本轮共同候选待审：0（按 v8 自动保留）": "Shared candidates pending this round: 0 (automatically preserved by v8)",
})
_JA.update({
    "继续会基于当前文档再次执行，可能改变已有结果。": "続行すると現在の文書を基準に再実行され、既存の結果が変わる可能性があります。",
    "如果想从处理前重新开始，请先使用「清空处理后」或「重新载入处理前」。": "処理前の状態からやり直す場合は、先に「処理後をクリア」または「処理前を再読込」を使用してください。",
    "是否继续？": "続行しますか？",
    "继续吗？": "続行しますか？",
    "可直接勾选步骤运行后处理。": "手順を選択して、そのまま後処理を実行できます。",
    "勾选「前后书剥离」等步骤运行后处理，可清理残留的样板文字。": "「前後付録の除去」などを選択して後処理を実行すると、残った定型文を除去できます。",
    "请保持一行对应一个文本块；删除空行可以，但不要合并或拆分块。": "1行を1テキストブロックに対応させてください。空行の削除はできますが、ブロックの結合や分割はしないでください。",
    "AI 排版结果中的 block 内部换行不会影响 EPUB；但手动改变段落数量时，无法安全映射回原结构。请撤销段落合并/拆分，或重新执行 AI 纠错排版。": "AI組版結果の block 内改行はEPUBに影響しませんが、段落数を手動で変更すると元の構造へ安全に戻せません。段落の結合/分割を取り消すか、AI修正・組版を再実行してください。",
    "仍可手动填写模型名称。": "モデル名は引き続き手動入力できます。",
    "建议在“查看AI修改”中取消勾选并保留原文。仍要继续吗？": "「AI変更を表示」でチェックを外し、原文を保持することを推奨します。それでも続行しますか？",
    "当前结果已同步 Formatter/EPUB；原 OCR、外部 OCR、AI 和参考原文版本仍独立保留。": "現在の結果はFormatter/EPUBへ同期済みです。元OCR・外部OCR・AI・参照原文の各バージョンは独立して保持されます。",
    "只修改 edited_text 或 Markdown 校对结果区，不要改动 ID 和结构清单。": "edited_text またはMarkdownの校正結果欄だけを変更し、IDや構造マニフェストは変更しないでください。",
    "交给大模型时只修改 edited_text 或 Markdown 的“大模型校对结果”区域。": "LLMへ渡す際は edited_text またはMarkdownの「LLM校正結果」欄だけを変更してください。",
    "大模型可在 editable_conflict.model_edits 中只修正错误模型，也可选填 ai_verdict.final_text 作为最终融合裁决；上一轮 accepted 结果在新包中只作为参考，可由后续 AI 提交更好的 final_text：": "LLMは editable_conflict.model_edits で誤ったモデルだけを修正でき、ai_verdict.final_text を最終融合裁決として任意入力できます。前回 accepted の結果は新しいパッケージでは参照のみで、後続AIがより良い final_text に置換できます：",
    "已直接恢复 OCR 文字、物理列、候选和人工选择，没有重新运行 OCR。": "OCR文字・物理列・候補・手動選択を直接復元し、OCRは再実行していません。",
    "AI 结果按稳定列 ID 累积合并；后续已接受结果可替换同句旧 AI，未决结果不会反向清空。NDLOCR、48px、Apple Vision 等原文和原分歧始终保留。": "AI結果は安定列ID単位で累積統合します。後続の採用結果は同一文の旧AI結果を置換できますが、未決結果が過去の結果を消すことはありません。NDLOCR・48px・Apple Visionなどの原文と元の差分は常に保持されます。",
    "已包含锁定 Ruby sidecar、AI 正文模板、最终 EPUB 构建器和 Ruby 验证器。": "ロック済みRuby sidecar、AI本文テンプレート、最終EPUBビルダー、Ruby検証器を含みます。",
    "融合 JSON 和稳定 ID 骨架 EPUB 已打包：": "融合JSONと安定ID付き骨格EPUBをパッケージ化しました：",
    "原子事务在任一成员上选择/撤销时会整组同步；确认后再点击“应用融合稿”。": "原子トランザクションは、いずれかのメンバーを選択/解除するとグループ全体が同期します。確認後に「融合稿を適用」をクリックしてください。",
    "允许新增或删除换行，请点击“重新自动对齐”后再继续。": "改行の追加・削除は可能です。「自動再整列」をクリックしてから続行してください。",
    "本操作只在本次确认后执行。更新会先下载和校验，再替换模型；NDLOCR-Lite 与 48px AR 会保留一个本地回退备份。": "この操作は今回の確認後にだけ実行されます。更新はダウンロードと検証後にモデルを置換し、NDLOCR-Lite と 48px AR はローカルのロールバック用バックアップを1つ保持します。",
    "不会更新 OCR 模型，也不会删除虚拟环境、模型缓存、书籍、输出和日志。更新完成后需要重启程序。": "OCRモデルは更新せず、仮想環境・モデルキャッシュ・書籍・出力・ログも削除しません。更新後はアプリの再起動が必要です。",
    "请关闭并重新启动 Novel Formatter。": "Novel Formatterを終了して再起動してください。",
    "构建期间当前正文已经切换，因此未把旧包预览安装到新书工作区。": "ビルド中に現在の本文が切り替わったため、旧パッケージのプレビューを新しい本のワークスペースへ導入しませんでした。",
    "文本框已获得焦点，仍可从 macOS 输入菜单切换到日语输入法或系统手写输入。": "テキスト欄にフォーカスがあります。macOSの入力メニューから日本語入力またはシステム手書き入力へ切り替えられます。",
    "人工纠错工作台未能打开，将继续使用完整的普通 OCR 底稿。": "手動修正ワークベンチを開けなかったため、完全な通常OCR下書きを引き続き使用します。",
    "请先重新对齐": "先に再整列してください",
    "原始多模型对齐：保持不变": "元の複数モデル整列：変更なし",
    "原始 OCR 实际回写：0 列 / 0 模型行": "元OCRへの実書き戻し：0列 / 0モデル行",
    "本轮共同候选待审：0（按 v8 自动保留）": "今回の共通候補の要確認：0（v8規則で自動保持）",
})


def _translate_risk_details(value: str, language: str) -> str:
    text = str(value)
    if language == LANG_EN:
        text = re.sub(r"(\d+) 组高风险修改", r"\1 high-risk change group(s)", text)
        text = re.sub(r"(\d+) 组与参考草稿明显相反的修改", r"\1 change group(s) clearly opposed by the reference draft", text)
        return text.replace("、", ", ")
    text = re.sub(r"(\d+) 组高风险修改", r"高リスク変更 \1 グループ", text)
    text = re.sub(r"(\d+) 组与参考草稿明显相反的修改", r"参照草稿と明確に反する変更 \1 グループ", text)
    return text.replace("、", "、")


_DIALOG_LINE_PATTERNS[LANG_EN].extend([
    (re.compile(r"当前勾选结果中仍采用了(.+)。这些修改可能涉及句序重排、引号损坏、对白粘连、大幅改写，或把草稿中已有的正确表达改坏。"), lambda m: f"The current selection still accepts {_translate_risk_details(m.group(1), LANG_EN)}. These changes may involve sentence reordering, damaged quotation marks, merged dialogue, extensive rewriting, or damage to text that was already correct in the draft."),
    (re.compile(r"修改 (\d+) 个块，删除 (\d+) 个重复/残片块；"), lambda m: f"Changed {m.group(1)} block(s) and removed {m.group(2)} duplicate/fragment block(s);"),
    (re.compile(r"边界重复 (\d+)，对白拆分 (\d+)，类型修复 (\d+)，引号恢复 (\d+)，跨块引号接回 (\d+)，OCR混淆修复 (\d+)。"), lambda m: f"boundary overlaps {m.group(1)}, dialogue splits {m.group(2)}, type repairs {m.group(3)}, quote restorations {m.group(4)}, cross-block quote joins {m.group(5)}, OCR-confusable repairs {m.group(6)}."),
    (re.compile(r"高风险问题：(\d+) → (\d+)。"), lambda m: f"High-risk issues: {m.group(1)} → {m.group(2)}."),
    (re.compile(r"翻译阻断：(\d+) → (\d+)。"), lambda m: f"Translation blockers: {m.group(1)} → {m.group(2)}."),
    (re.compile(r"正文100%来自右侧；正文 (\d+) 段/(\d+) 字；目录 (\d+) 项；图片 (\d+) 张（待确认 (\d+)）"), lambda m: f"Body text is 100% from the right pane; {m.group(1)} paragraphs / {m.group(2)} chars; {m.group(3)} TOC entries; {m.group(4)} images ({m.group(5)} pending)"),
    (re.compile(r"正文完整性异常；正文 (\d+) 段/(\d+) 字；目录 (\d+) 项；图片 (\d+) 张（待确认 (\d+)）"), lambda m: f"Body-text integrity anomaly; {m.group(1)} paragraphs / {m.group(2)} chars; {m.group(3)} TOC entries; {m.group(4)} images ({m.group(5)} pending)"),
    (re.compile(r"已彻底移除旧 OCR 正文块：(\d+)"), lambda m: f"Old OCR body blocks removed completely: {m.group(1)}"),
    (re.compile(r"显式插图标记：(\d+)/(\d+)"), lambda m: f"Explicit illustration markers: {m.group(1)}/{m.group(2)}"),
    (re.compile(r"待确认图片：(\d+)"), lambda m: f"Images pending confirmation: {m.group(1)}"),
    (re.compile(r"已导出 (\d+) 个可校对正文块："), lambda m: f"Exported {m.group(1)} proofreadable body blocks:"),
    (re.compile(r"已导出 (\d+) 个 OCR 模型、(\d+) 个对齐句组："), lambda m: f"Exported {m.group(1)} OCR model(s) and {m.group(2)} aligned sentence group(s):"),
    (re.compile(r"真正分歧总数：(\d+)"), lambda m: f"True disagreements: {m.group(1)}"),
    (re.compile(r"两模型共同候选（自动保留）：(\d+)"), lambda m: f"Two-model shared candidates (auto-preserved): {m.group(1)}"),
    (re.compile(r"此前裁决保持锁定：(\d+)"), lambda m: f"Previous decisions kept locked: {m.group(1)}"),
    (re.compile(r"此前已接受结果重新开放复审：(\d+)"), lambda m: f"Previously accepted results reopened for review: {m.group(1)}"),
    (re.compile(r"其中旧逐模型结果迁移：(\d+)"), lambda m: f"Legacy per-model results migrated: {m.group(1)}"),
    (re.compile(r"本轮真正分歧待审：(\d+)"), lambda m: f"True disagreements pending this round: {m.group(1)}"),
    (re.compile(r"本轮合计待审：(\d+)"), lambda m: f"Total pending this round: {m.group(1)}"),
    (re.compile(r"过期裁决重新待审：(\d+)"), lambda m: f"Stale decisions reopened: {m.group(1)}"),
    (re.compile(r"锁定真正一致行：(\d+)"), lambda m: f"Locked truly-consistent rows: {m.group(1)}"),
    (re.compile(r"视觉证据：(\d+) 张"), lambda m: f"Visual evidence: {m.group(1)} image(s)"),
    (re.compile(r"可恢复 OCR 会话：(是|否)"), lambda m: f"Restorable OCR session: {'Yes' if m.group(1) == '是' else 'No'}"),
    (re.compile(r"对齐句：(\d+)"), lambda m: f"Aligned sentences: {m.group(1)}"),
    (re.compile(r"重新绑定图片：(\d+)"), lambda m: f"Rebound images: {m.group(1)}"),
    (re.compile(r"JSON 中逐模型修改建议：(\d+) 列 / (\d+) 模型行"), lambda m: f"Per-model correction suggestions in JSON: {m.group(1)} columns / {m.group(2)} model rows"),
    (re.compile(r"涉及模型：(.*)"), lambda m: f"Models involved: {m.group(1)}"),
    (re.compile(r"本次真正新增/改进并采用 AI 候选：(\d+)"), lambda m: f"New/improved AI candidates actually adopted this time: {m.group(1)}"),
    (re.compile(r"累计导入 AI 裁决包：(\d+)"), lambda m: f"AI adjudication packages imported cumulatively: {m.group(1)}"),
    (re.compile(r"当前累计有效 AI 裁决：(\d+)"), lambda m: f"Currently valid AI decisions: {m.group(1)}"),
    (re.compile(r"本包新增裁决：(\d+)；改进替换：(\d+)"), lambda m: f"New decisions in this package: {m.group(1)}; improved replacements: {m.group(2)}"),
    (re.compile(r"继续可见的原始分歧：(\d+)"), lambda m: f"Original disagreements still visible: {m.group(1)}"),
    (re.compile(r"三方证据冲突（仅报告，不覆盖）：(\d+)"), lambda m: f"Three-way evidence conflicts (report only, no overwrite): {m.group(1)}"),
    (re.compile(r"旧逐模型结果安全迁移：(\d+)"), lambda m: f"Legacy per-model results safely migrated: {m.group(1)}"),
    (re.compile(r"旧式共同候选自动恢复：(\d+)"), lambda m: f"Legacy shared candidates automatically restored: {m.group(1)}"),
    (re.compile(r"从续作包恢复的已完成裁决：(\d+)"), lambda m: f"Completed decisions restored from continuation package: {m.group(1)}"),
    (re.compile(r"仍需最终判断：(\d+)"), lambda m: f"Still needs final judgment: {m.group(1)}"),
    (re.compile(r"拒绝占位符裁决：(\d+)"), lambda m: f"Placeholder decisions rejected: {m.group(1)}"),
    (re.compile(r"拒绝可疑拉丁字母裁决：(\d+)"), lambda m: f"Suspicious Latin-letter decisions rejected: {m.group(1)}"),
    (re.compile(r"保留未受影响人工选择：(\d+)"), lambda m: f"Unaffected manual selections preserved: {m.group(1)}"),
    (re.compile(r"正文条目：(\d+)"), lambda m: f"Body entries: {m.group(1)}"),
    (re.compile(r"锁定 Ruby：(\d+) 组（(开启|关闭)）"), lambda m: f"Locked Ruby: {m.group(1)} group(s) ({'enabled' if m.group(2) == '开启' else 'disabled'})"),
    (re.compile(r"已导出 (\d+) 个 UTF-8 文本文件到："), lambda m: f"Exported {m.group(1)} UTF-8 text file(s) to:"),
    (re.compile(r"将从 (.+) / (.+) 更新程序代码。"), lambda m: f"Application source will be updated from {m.group(1)} / {m.group(2)}."),
    (re.compile(r"本地：v(.+)"), lambda m: f"Local: v{m.group(1)}"),
    (re.compile(r"远端：v(.+) · (.+)"), lambda m: f"Remote: v{m.group(1)} · {m.group(2)}"),
    (re.compile(r"无法读取 OCR 模型本地状态："), lambda m: "Cannot read local OCR model status:"),
    (re.compile(r"(.+) 不属于“(.+)”识别链。两个 OCR 模式使用独立引擎集合，切换回日文竖排后仍可继续使用该引擎。"), lambda m: f"{m.group(1)} is not part of the “{m.group(2)}” recognition chain. The two OCR modes use independent engine sets; this engine remains available after switching back to Japanese Vertical."),
    (re.compile(r"右侧正文与套入版面后的正文不完全一致，已停止应用。"), lambda m: "The right-side body text does not exactly match the body text after layout projection, so applying was stopped."),
    (re.compile(r"真正分歧总数：(\d+) · 本轮待审：(\d+) · 视觉证据：(\d+) 张"), lambda m: f"True disagreements: {m.group(1)} · Pending this round: {m.group(2)} · Visual evidence: {m.group(3)} image(s)"),
    (re.compile(r"裁决包：(.*)"), lambda m: f"Adjudication package: {m.group(1)}"),
    (re.compile(r"多模型 OCR 会话已恢复：(\d+) 个模型 · (\d+) 个对齐句 · 重新绑定图片 (\d+)。没有重新运行 OCR。"), lambda m: f"Multi-model OCR session restored: {m.group(1)} model(s) · {m.group(2)} aligned sentence(s) · {m.group(3)} image(s) rebound. OCR was not rerun."),
    (re.compile(r"AI OCR 裁决已非破坏式导入：本包新增 (\d+)、改进 (\d+)；当前有效 (\d+)，仍需判断 (\d+)。原始各模型 OCR、物理列和对齐均保持不变。"), lambda m: f"AI OCR adjudication imported non-destructively: {m.group(1)} new, {m.group(2)} improved; {m.group(3)} currently valid, {m.group(4)} still need review. Original model OCR, physical columns and alignment are unchanged."),
    (re.compile(r"已导出 (.+)：正文 (\d+) 条 · 需复核 (\d+) 条 · ZIP ([\d.]+) MB"), lambda m: f"Exported {translate_text(m.group(1), LANG_EN)}: {m.group(2)} body items · {m.group(3)} need review · ZIP {m.group(4)} MB"),
    (re.compile(r"AI 修复结果已载入：(\d+) 条 · 已选择 (\d+) · 待人工 (\d+) · 原子事务 (\d+)。原始 OCR 和结构未被覆盖。"), lambda m: f"AI repair result loaded: {m.group(1)} update(s) · {m.group(2)} selected · {m.group(3)} manual review · {m.group(4)} atomic transaction(s). Original OCR and structure were not overwritten."),
])

_DIALOG_LINE_PATTERNS[LANG_JA].extend([
    (re.compile(r"当前勾选结果中仍采用了(.+)。这些修改可能涉及句序重排、引号损坏、对白粘连、大幅改写，或把草稿中已有的正确表达改坏。"), lambda m: f"現在の選択には {_translate_risk_details(m.group(1), LANG_JA)} がまだ採用されています。これらは文順の変更、引用符の破損、台詞の結合、大幅な書き換え、または草稿ですでに正しかった表現を損なう可能性があります。"),
    (re.compile(r"修改 (\d+) 个块，删除 (\d+) 个重复/残片块；"), lambda m: f"{m.group(1)} ブロックを変更し、重複/断片ブロック {m.group(2)} 件を削除；"),
    (re.compile(r"边界重复 (\d+)，对白拆分 (\d+)，类型修复 (\d+)，引号恢复 (\d+)，跨块引号接回 (\d+)，OCR混淆修复 (\d+)。"), lambda m: f"境界重複 {m.group(1)}、台詞分割 {m.group(2)}、型修復 {m.group(3)}、引用符復元 {m.group(4)}、ブロック跨ぎ引用符接続 {m.group(5)}、OCR類似字修復 {m.group(6)}。"),
    (re.compile(r"高风险问题：(\d+) → (\d+)。"), lambda m: f"高リスク問題：{m.group(1)} → {m.group(2)}。"),
    (re.compile(r"翻译阻断：(\d+) → (\d+)。"), lambda m: f"翻訳ブロッカー：{m.group(1)} → {m.group(2)}。"),
    (re.compile(r"正文100%来自右侧；正文 (\d+) 段/(\d+) 字；目录 (\d+) 项；图片 (\d+) 张（待确认 (\d+)）"), lambda m: f"本文は100%右側由来；本文 {m.group(1)} 段落/{m.group(2)} 文字；目次 {m.group(3)} 件；画像 {m.group(4)} 枚（要確認 {m.group(5)}）"),
    (re.compile(r"正文完整性异常；正文 (\d+) 段/(\d+) 字；目录 (\d+) 项；图片 (\d+) 张（待确认 (\d+)）"), lambda m: f"本文整合性異常；本文 {m.group(1)} 段落/{m.group(2)} 文字；目次 {m.group(3)} 件；画像 {m.group(4)} 枚（要確認 {m.group(5)}）"),
    (re.compile(r"已彻底移除旧 OCR 正文块：(\d+)"), lambda m: f"旧OCR本文ブロックを完全削除：{m.group(1)}"),
    (re.compile(r"显式插图标记：(\d+)/(\d+)"), lambda m: f"明示的な挿絵マーカー：{m.group(1)}/{m.group(2)}"),
    (re.compile(r"待确认图片：(\d+)"), lambda m: f"要確認画像：{m.group(1)}"),
    (re.compile(r"已导出 (\d+) 个可校对正文块："), lambda m: f"校正可能な本文ブロックを {m.group(1)} 件書き出しました："),
    (re.compile(r"已导出 (\d+) 个 OCR 模型、(\d+) 个对齐句组："), lambda m: f"OCRモデル {m.group(1)} 件、整列文グループ {m.group(2)} 件を書き出しました："),
    (re.compile(r"真正分歧总数：(\d+)"), lambda m: f"真の不一致総数：{m.group(1)}"),
    (re.compile(r"两模型共同候选（自动保留）：(\d+)"), lambda m: f"2モデル共通候補（自動保持）：{m.group(1)}"),
    (re.compile(r"此前裁决保持锁定：(\d+)"), lambda m: f"以前の裁決をロック維持：{m.group(1)}"),
    (re.compile(r"此前已接受结果重新开放复审：(\d+)"), lambda m: f"以前の採用結果を再レビュー対象に戻した件数：{m.group(1)}"),
    (re.compile(r"其中旧逐模型结果迁移：(\d+)"), lambda m: f"うち旧モデル別結果の移行：{m.group(1)}"),
    (re.compile(r"本轮真正分歧待审：(\d+)"), lambda m: f"今回の真の不一致・要確認：{m.group(1)}"),
    (re.compile(r"本轮合计待审：(\d+)"), lambda m: f"今回の要確認合計：{m.group(1)}"),
    (re.compile(r"过期裁决重新待审：(\d+)"), lambda m: f"期限切れ裁決の再確認：{m.group(1)}"),
    (re.compile(r"锁定真正一致行：(\d+)"), lambda m: f"真に一致してロックした行：{m.group(1)}"),
    (re.compile(r"视觉证据：(\d+) 张"), lambda m: f"視覚証拠：{m.group(1)} 枚"),
    (re.compile(r"可恢复 OCR 会话：(是|否)"), lambda m: f"復元可能なOCRセッション：{'はい' if m.group(1) == '是' else 'いいえ'}"),
    (re.compile(r"对齐句：(\d+)"), lambda m: f"整列文：{m.group(1)}"),
    (re.compile(r"重新绑定图片：(\d+)"), lambda m: f"画像の再バインド：{m.group(1)}"),
    (re.compile(r"JSON 中逐模型修改建议：(\d+) 列 / (\d+) 模型行"), lambda m: f"JSON内のモデル別修正提案：{m.group(1)} 列 / {m.group(2)} モデル行"),
    (re.compile(r"涉及模型：(.*)"), lambda m: f"対象モデル：{m.group(1)}"),
    (re.compile(r"本次真正新增/改进并采用 AI 候选：(\d+)"), lambda m: f"今回実際に新規/改善して採用したAI候補：{m.group(1)}"),
    (re.compile(r"累计导入 AI 裁决包：(\d+)"), lambda m: f"累計AI裁決パッケージ読み込み数：{m.group(1)}"),
    (re.compile(r"当前累计有效 AI 裁决：(\d+)"), lambda m: f"現在の有効AI裁決累計：{m.group(1)}"),
    (re.compile(r"本包新增裁决：(\d+)；改进替换：(\d+)"), lambda m: f"このパッケージの新規裁決：{m.group(1)}；改善置換：{m.group(2)}"),
    (re.compile(r"继续可见的原始分歧：(\d+)"), lambda m: f"引き続き表示する元の不一致：{m.group(1)}"),
    (re.compile(r"三方证据冲突（仅报告，不覆盖）：(\d+)"), lambda m: f"3-way証拠競合（報告のみ・上書きなし）：{m.group(1)}"),
    (re.compile(r"旧逐模型结果安全迁移：(\d+)"), lambda m: f"旧モデル別結果の安全な移行：{m.group(1)}"),
    (re.compile(r"旧式共同候选自动恢复：(\d+)"), lambda m: f"旧形式の共通候補を自動復元：{m.group(1)}"),
    (re.compile(r"从续作包恢复的已完成裁决：(\d+)"), lambda m: f"継続パッケージから復元した完了裁決：{m.group(1)}"),
    (re.compile(r"仍需最终判断：(\d+)"), lambda m: f"最終判断が必要：{m.group(1)}"),
    (re.compile(r"拒绝占位符裁决：(\d+)"), lambda m: f"プレースホルダー裁決を拒否：{m.group(1)}"),
    (re.compile(r"拒绝可疑拉丁字母裁决：(\d+)"), lambda m: f"疑わしいラテン文字裁決を拒否：{m.group(1)}"),
    (re.compile(r"保留未受影响人工选择：(\d+)"), lambda m: f"影響のない手動選択を保持：{m.group(1)}"),
    (re.compile(r"正文条目：(\d+)"), lambda m: f"本文項目：{m.group(1)}"),
    (re.compile(r"锁定 Ruby：(\d+) 组（(开启|关闭)）"), lambda m: f"ロックRuby：{m.group(1)} 組（{'有効' if m.group(2) == '开启' else '無効'}）"),
    (re.compile(r"已导出 (\d+) 个 UTF-8 文本文件到："), lambda m: f"UTF-8テキストファイルを {m.group(1)} 件書き出しました："),
    (re.compile(r"将从 (.+) / (.+) 更新程序代码。"), lambda m: f"{m.group(1)} / {m.group(2)} からアプリのソースを更新します。"),
    (re.compile(r"本地：v(.+)"), lambda m: f"ローカル：v{m.group(1)}"),
    (re.compile(r"远端：v(.+) · (.+)"), lambda m: f"リモート：v{m.group(1)} · {m.group(2)}"),
    (re.compile(r"无法读取 OCR 模型本地状态："), lambda m: "OCRモデルのローカル状態を読み取れません："),
    (re.compile(r"(.+) 不属于“(.+)”识别链。两个 OCR 模式使用独立引擎集合，切换回日文竖排后仍可继续使用该引擎。"), lambda m: f"{m.group(1)} は「{m.group(2)}」認識チェーンには属しません。2つのOCRモードは独立したエンジン集合を使うため、日本語縦書きへ戻した後もこのエンジンを使用できます。"),
    (re.compile(r"右侧正文与套入版面后的正文不完全一致，已停止应用。"), lambda m: "右側本文とレイアウトへ投影した本文が完全一致しないため、適用を停止しました。"),
    (re.compile(r"真正分歧总数：(\d+) · 本轮待审：(\d+) · 视觉证据：(\d+) 张"), lambda m: f"真の不一致総数：{m.group(1)} · 今回の要確認：{m.group(2)} · 視覚証拠：{m.group(3)} 枚"),
    (re.compile(r"裁决包：(.*)"), lambda m: f"裁決パッケージ：{m.group(1)}"),
    (re.compile(r"多模型 OCR 会话已恢复：(\d+) 个模型 · (\d+) 个对齐句 · 重新绑定图片 (\d+)。没有重新运行 OCR。"), lambda m: f"複数モデルOCRセッションを復元しました：{m.group(1)} モデル · {m.group(2)} 整列文 · 画像再バインド {m.group(3)}。OCRは再実行していません。"),
    (re.compile(r"AI OCR 裁决已非破坏式导入：本包新增 (\d+)、改进 (\d+)；当前有效 (\d+)，仍需判断 (\d+)。原始各模型 OCR、物理列和对齐均保持不变。"), lambda m: f"AI OCR裁決を非破壊で読み込みました：新規 {m.group(1)}、改善 {m.group(2)}；現在有効 {m.group(3)}、要判断 {m.group(4)}。各モデルの元OCR・物理列・整列は変更していません。"),
    (re.compile(r"已导出 (.+)：正文 (\d+) 条 · 需复核 (\d+) 条 · ZIP ([\d.]+) MB"), lambda m: f"{translate_text(m.group(1), LANG_JA)}を書き出しました：本文 {m.group(2)} 件 · 要確認 {m.group(3)} 件 · ZIP {m.group(4)} MB"),
    (re.compile(r"AI 修复结果已载入：(\d+) 条 · 已选择 (\d+) · 待人工 (\d+) · 原子事务 (\d+)。原始 OCR 和结构未被覆盖。"), lambda m: f"AI修復結果を読み込みました：{m.group(1)} 件 · 選択済み {m.group(2)} · 手動確認 {m.group(3)} · 原子トランザクション {m.group(4)}。元OCRと構造は上書きしていません。"),
])

_EN.update({
    "上传整个 ZIP。大模型只能裁决 03_conflict_items.jsonl 中的 ID，必须运行 tools/apply_decisions.py 和 tools/validate_epub.py，并交付最终 EPUB 与审计文件。": "Upload the entire ZIP. The LLM may adjudicate only IDs in 03_conflict_items.jsonl, must run tools/apply_decisions.py and tools/validate_epub.py, and must deliver the final EPUB plus audit files.",
    "上传整个 ZIP。12_stable_text_map.jsonl 是唯一默认文字母本；full_fusion_evidence.json 完整融合证据只保存一次。大模型必须运行 tools/validate_final_epub.py，并同时交付最终 EPUB 与完整审计文件。": "Upload the entire ZIP. 12_stable_text_map.jsonl is the sole default text master; the complete fusion evidence in full_fusion_evidence.json is stored only once. The LLM must run tools/validate_final_epub.py and deliver both the final EPUB and the complete audit files.",
})
_JA.update({
    "上传整个 ZIP。大模型只能裁决 03_conflict_items.jsonl 中的 ID，必须运行 tools/apply_decisions.py 和 tools/validate_epub.py，并交付最终 EPUB 与审计文件。": "ZIP全体をアップロードしてください。LLMが裁決できるのは 03_conflict_items.jsonl 内のIDだけです。tools/apply_decisions.py と tools/validate_epub.py を実行し、最終EPUBと監査ファイルを納品する必要があります。",
    "上传整个 ZIP。12_stable_text_map.jsonl 是唯一默认文字母本；full_fusion_evidence.json 完整融合证据只保存一次。大模型必须运行 tools/validate_final_epub.py，并同时交付最终 EPUB 与完整审计文件。": "ZIP全体をアップロードしてください。12_stable_text_map.jsonl が唯一の既定テキスト母本で、full_fusion_evidence.json の完全融合証拠は1回だけ保存されます。LLMは tools/validate_final_epub.py を実行し、最終EPUBと完全な監査ファイルを同時に納品する必要があります。",
})
_DIALOG_LINE_PATTERNS[LANG_EN].extend([
    (re.compile(r"模式：(.*)"), lambda m: f"Mode: {translate_text(m.group(1), LANG_EN)}"),
    (re.compile(r"文件夹：(.*)"), lambda m: f"Folder: {m.group(1)}"),
    (re.compile(r"整包 ZIP：(.*)"), lambda m: f"Full ZIP: {m.group(1)}"),
    (re.compile(r"实际 ZIP：([\d.]+) MB"), lambda m: f"Actual ZIP: {m.group(1)} MB"),
    (re.compile(r"入口命令：(.*)"), lambda m: f"Entry command: {m.group(1)}"),
    (re.compile(r"完整融合 JSON：(.*)"), lambda m: f"Complete fusion JSON: {m.group(1)}"),
    (re.compile(r"结构预检：(.*)"), lambda m: f"Structure preflight: {m.group(1)}"),
    (re.compile(r"独立重建源：(.*)"), lambda m: f"Independent rebuild source: {m.group(1)}"),
    (re.compile(r"框架 EPUB：(.*)"), lambda m: f"Framework EPUB: {m.group(1)}"),
    (re.compile(r"建议最终文件名：(.*)"), lambda m: f"Suggested final filename: {m.group(1)}"),
    (re.compile(r"逻辑章节：(\d+)"), lambda m: f"Logical chapters: {m.group(1)}"),
    (re.compile(r"成品图片：(\d+)"), lambda m: f"Publication images: {m.group(1)}"),
    (re.compile(r"锁定一致条目：(\d+)"), lambda m: f"Locked consensus entries: {m.group(1)}"),
    (re.compile(r"需要文字复核：(\d+)"), lambda m: f"Text review required: {m.group(1)}"),
    (re.compile(r"原子跨度：(\d+)"), lambda m: f"Atomic spans: {m.group(1)}"),
    (re.compile(r"独立插图页：(\d+)"), lambda m: f"Standalone illustration pages: {m.group(1)}"),
    (re.compile(r"视觉证据页：(\d+)"), lambda m: f"Visual-evidence pages: {m.group(1)}"),
    (re.compile(r"视觉图片文件：(\d+)"), lambda m: f"Visual image files: {m.group(1)}"),
    (re.compile(r"选择性视觉裁切记录：(\d+)"), lambda m: f"Selective visual-crop records: {m.group(1)}"),
    (re.compile(r"致命未映射正文列：(\d+)"), lambda m: f"Fatal unmapped body columns: {m.group(1)}"),
    (re.compile(r"出版参考证据：(已显式包含|未包含)"), lambda m: f"Publication-reference evidence: {'explicitly included' if m.group(1) == '已显式包含' else 'not included'}"),
])
_DIALOG_LINE_PATTERNS[LANG_JA].extend([
    (re.compile(r"模式：(.*)"), lambda m: f"モード：{translate_text(m.group(1), LANG_JA)}"),
    (re.compile(r"文件夹：(.*)"), lambda m: f"フォルダ：{m.group(1)}"),
    (re.compile(r"整包 ZIP：(.*)"), lambda m: f"全ZIP：{m.group(1)}"),
    (re.compile(r"实际 ZIP：([\d.]+) MB"), lambda m: f"実ZIP：{m.group(1)} MB"),
    (re.compile(r"入口命令：(.*)"), lambda m: f"入口コマンド：{m.group(1)}"),
    (re.compile(r"完整融合 JSON：(.*)"), lambda m: f"完全融合JSON：{m.group(1)}"),
    (re.compile(r"结构预检：(.*)"), lambda m: f"構造事前検査：{m.group(1)}"),
    (re.compile(r"独立重建源：(.*)"), lambda m: f"独立再構築ソース：{m.group(1)}"),
    (re.compile(r"框架 EPUB：(.*)"), lambda m: f"骨格EPUB：{m.group(1)}"),
    (re.compile(r"建议最终文件名：(.*)"), lambda m: f"推奨最終ファイル名：{m.group(1)}"),
    (re.compile(r"逻辑章节：(\d+)"), lambda m: f"論理章：{m.group(1)}"),
    (re.compile(r"成品图片：(\d+)"), lambda m: f"完成画像：{m.group(1)}"),
    (re.compile(r"锁定一致条目：(\d+)"), lambda m: f"ロック済み一致項目：{m.group(1)}"),
    (re.compile(r"需要文字复核：(\d+)"), lambda m: f"文字確認が必要：{m.group(1)}"),
    (re.compile(r"原子跨度：(\d+)"), lambda m: f"原子span：{m.group(1)}"),
    (re.compile(r"独立插图页：(\d+)"), lambda m: f"独立挿絵ページ：{m.group(1)}"),
    (re.compile(r"视觉证据页：(\d+)"), lambda m: f"視覚証拠ページ：{m.group(1)}"),
    (re.compile(r"视觉图片文件：(\d+)"), lambda m: f"視覚画像ファイル：{m.group(1)}"),
    (re.compile(r"选择性视觉裁切记录：(\d+)"), lambda m: f"選択的視覚crop記録：{m.group(1)}"),
    (re.compile(r"致命未映射正文列：(\d+)"), lambda m: f"致命的な未マップ本文列：{m.group(1)}"),
    (re.compile(r"出版参考证据：(已显式包含|未包含)"), lambda m: f"出版参照証拠：{'明示的に含む' if m.group(1) == '已显式包含' else '含まない'}"),
])

_EN.update({
    "选择 AI 裁决报告目录": "Choose AI adjudication report folder",
    "无法裁决": "Unable to adjudicate",
})
_JA.update({
    "选择 AI 裁决报告目录": "AI裁決レポートフォルダを選択",
    "无法裁决": "裁決できません",
})


# v32 role-based multi-model OCR scheduler.
_EN.update({
    "多模型 OCR 配置不可运行": "Multi-model OCR configuration cannot run",
})
_JA.update({
    "多模型 OCR 配置不可运行": "複数モデルOCR設定を実行できません",
})

# v5.3 persistent project workspace dialogs.
_EN.update({
    "新建项目": "New Project",
    "项目名称": "Project Name",
    "未选择项目": "No Project Selected",
    "请先新建或选择项目。": "Create or select a project first.",
    "选择 Novel Formatter 工作区": "Choose Novel Formatter Workspace",
    "选择已有 Novel Formatter 项目文件夹": "Choose Existing Novel Formatter Project Folder",
})
_JA.update({
    "新建项目": "新規プロジェクト",
    "项目名称": "プロジェクト名",
    "未选择项目": "プロジェクト未選択",
    "请先新建或选择项目。": "先にプロジェクトを作成または選択してください。",
    "选择 Novel Formatter 工作区": "Novel Formatter ワークスペースを選択",
    "选择已有 Novel Formatter 项目文件夹": "既存の Novel Formatter プロジェクトフォルダを選択",
})

# v5.4 project backup / integrity dialogs.
_EN.update({
    "导入 Novel Formatter 项目备份": "Import Novel Formatter Project Backup",
    "Novel Formatter 项目备份 (*.zip);;ZIP 文件 (*.zip)": "Novel Formatter Project Backup (*.zip);;ZIP Files (*.zip)",
    "导出完整项目备份": "Export Complete Project Backup",
    "Novel Formatter 项目备份 (*.zip)": "Novel Formatter Project Backup (*.zip)",
    "项目备份完成": "Project Backup Complete",
    "项目检查": "Project Check",
    "项目存储优化完成": "Project Storage Optimization Complete",
})
_JA.update({
    "导入 Novel Formatter 项目备份": "Novel Formatter プロジェクトバックアップを読み込む",
    "Novel Formatter 项目备份 (*.zip);;ZIP 文件 (*.zip)": "Novel Formatter プロジェクトバックアップ (*.zip);;ZIPファイル (*.zip)",
    "导出完整项目备份": "完全プロジェクトバックアップを書き出す",
    "Novel Formatter 项目备份 (*.zip)": "Novel Formatter プロジェクトバックアップ (*.zip)",
    "项目备份完成": "プロジェクトバックアップ完了",
    "项目检查": "プロジェクト検査",
    "项目存储优化完成": "プロジェクトストレージ最適化完了",
})

# Current-only adjudication package dialogs (development schema).
_EN.update({
    "当前 AI OCR 裁决包 (*.zip)": "Current AI OCR Adjudication Package (*.zip)",
    "当前 AI OCR 裁决结果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)": "Current AI OCR Adjudication Result (*.json *.zip);;JSON (*.json);;ZIP (*.zip)",
    "当前 V5 裁决结果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)": "Current V5 Adjudication Result (*.json *.zip);;JSON (*.json);;ZIP (*.zip)",
})
_JA.update({
    "当前 AI OCR 裁决包 (*.zip)": "現在のAI OCR裁決パッケージ (*.zip)",
    "当前 AI OCR 裁决结果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)": "現在のAI OCR裁決結果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)",
    "当前 V5 裁决结果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)": "現在のV5裁決結果 (*.json *.zip);;JSON (*.json);;ZIP (*.zip)",
})

# Current workflow messages after removal of the legacy standalone text-edit workspaces.
_EN.update({
    "修改文字已按 block ID 完整覆盖并进入 Formatter、OCR 对比、图文对照和 EPUB。\n同一来源被更新，没有新增重复副本，也没有执行全文查找替换。": "Edited text was applied exactly by block ID and propagated to Formatter, OCR Compare, Image/Text Review, and EPUB.\nThe same source was updated; no duplicate copy was created and no whole-text search/replace was performed.",
    "当前单 OCR 结果已进入 Formatter、OCR 对比、图文对照和 EPUB。": "The current single-OCR result has entered Formatter, OCR Compare, Image/Text Review, and EPUB.",
    "融合稿已进入 Formatter、OCR 对比和 EPUB 工作流。\n每个候选框中的人工修改均已写入，模型原始结果没有被覆盖。": "The fusion draft has entered the Formatter, OCR Compare, and EPUB workflow.\nManual edits in every candidate box were saved; original model results were not overwritten.",
})
_JA.update({
    "修改文字已按 block ID 完整覆盖并进入 Formatter、OCR 对比、图文对照和 EPUB。\n同一来源被更新，没有新增重复副本，也没有执行全文查找替换。": "編集文字をblock ID単位で完全に適用し、Formatter・OCR比較・画像/テキスト校正・EPUBへ反映しました。\n同じソースを更新しており、重複コピーの追加や全文検索置換は行っていません。",
    "当前单 OCR 结果已进入 Formatter、OCR 对比、图文对照和 EPUB。": "現在の単一OCR結果をFormatter・OCR比較・画像/テキスト校正・EPUBへ反映しました。",
    "融合稿已进入 Formatter、OCR 对比和 EPUB 工作流。\n每个候选框中的人工修改均已写入，模型原始结果没有被覆盖。": "融合稿をFormatter・OCR比較・EPUBワークフローへ反映しました。\n各候補欄の手動編集は保存され、モデルの元結果は上書きしていません。",
})
